with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mocks.go"
outpkg: "mocks"
packages:
  sumni-finance-backend/internal/finance/domain/fundprovider:
    interfaces:
      Repository:
  sumni-finance-backend/internal/finance/domain/wallet:
    interfaces:
      Repository:
  sumni-finance-backend/internal/finance/domain/ledger:
    interfaces:
      Repository:
