name: "sumni-finance"

services:
  sumni-finance-backend:
    container_name: sumni-finance-backend
    build:
      context: docker/app-local
    volumes:
      # Source code volumes
      - ./internal:/app/internal
      - ./cmd:/app/cmd
      # Go module files
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      # Go cache volumes
      - ./.go/pkg:/app/go/pkg
      - ./.go-cache:/app/go-cache
    working_dir: /app
    ports:
      - "127.0.0.1:4000:$PORT" # App port
      - "127.0.0.1:40000:40000" # Delve debug port
    env_file:
      - .env
    environment:
      DEBUG: "${DEBUG:-false}"
      GOCACHE: /app/go-cache
    depends_on:
    - sumni-finance-db
    # - keycloak
    networks:
      - finance-app

  sumni-finance-db:
    image: postgres:17.6-alpine3.22
    container_name: sumni-finance-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sumni-finance
    healthcheck:
      test: pg_isready -U user -d sumni-finance
      interval: 1s
      retries: 120
      start_period: 2s
    networks:
      - finance-app
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql

  keycloak:
    image: quay.io/keycloak/keycloak:26.6
    container_name: keycloak_server
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://sumni-finance-db:5432/sumni-finance
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: keycloak
    ports:
      - "8080:8080"
    depends_on:
      sumni-finance-db:
        condition: service_healthy
    networks:
      - finance-app

networks:
  finance-app:

volumes:
  postgres_data:
