version: "3.8"
name: "wild-workouts"

services:
  sumni-finance-backend:
    container_name: sumni-finance-backend
    build:
      context: docker/app-local
    volumes:
      # Source code volumes
      - ./internal:/app/internal
      - ./cmd:/app/cmd
      # Go module files
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      # Go cache volumes
      - ./.go/pkg:/app/go/pkg
      - ./.go-cache:/app/go-cache
    working_dir: /app
    ports:
      - "127.0.0.1:4000:$PORT" # App port
      - "127.0.0.1:40000:40000" # Delve debug port
    env_file:
      - .env
    environment:
      DEBUG: "${DEBUG:-false}"
      GOCACHE: /go-cache
    depends_on:
    - sumni-finance-db
    # - keycloak

  sumni-finance-db:
    image: postgres:16-alpine
    container_name: sumni-finance-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sumni
      POSTGRES_PASSWORD: sumni
      POSTGRES_DB: sumni-finance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   container_name: keycloak_server
  #   command: start-dev --import-realm
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #     KC_HTTP_ENABLED: "true"
  #     KC_HOSTNAME_STRICT: "false"
  #     KC_HOSTNAME_STRICT_HTTPS: "false"
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./docker/keycloak:/opt/keycloak/data/import

networks:
  finance-app:

volumes:
  postgres_data:
