version: "3.8"
name: "wild-workouts"

services:
  sumni-finance-backend:
    container_name: sumni-finance-backend
    build:
      context: docker/app-local
    volumes:
      # Source code volumes
      - ./internal:/app/internal
      - ./cmd:/app/cmd
      # Go module files
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      # Go cache volumes
      - ./.go/pkg:/app/go/pkg
      - ./.go-cache:/app/go-cache
    working_dir: /app
    ports:
      - "127.0.0.1:4000:$PORT" # App port
      - "127.0.0.1:40000:40000" # Delve debug port
    env_file:
      - .env
    environment:
      DEBUG: "${DEBUG:-false}"
      GOCACHE: /app/go-cache
    depends_on:
    - sumni-finance-db
    # - keycloak

  postgres:
    image: postgres:17.6-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sumni-finance
    healthcheck:
      test: pg_isready -U user -d sumni-finance
      interval: 1s
      retries: 120
      start_period: 2s
    ports:
      - "5432:5432"

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: sumni-swagger-ui
    ports:
      - "127.0.0.1:8090:8080"
    volumes:
      - ./api/openapi/finance.yaml:/app/finance.yaml:ro
    environment:
      SWAGGER_JSON: /app/finance.yaml
    restart: always

  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   container_name: keycloak_server
  #   command: start-dev --import-realm
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #     KC_HTTP_ENABLED: "true"
  #     KC_HOSTNAME_STRICT: "false"
  #     KC_HOSTNAME_STRICT_HTTPS: "false"
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./docker/keycloak:/opt/keycloak/data/import

networks:
  finance-app:

volumes:
  postgres_data:
