// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"

	"github.com/oapi-codegen/runtime"
	"github.com/shopspring/decimal"
)

// CreateFundSourceRequest defines model for CreateFundSourceRequest.
type CreateFundSourceRequest struct {
	Currency    Currency           `json:"currency"`
	InitBalance Decimal            `json:"init_balance"`
	Metadata    FundSourceMetadata `json:"metadata"`
	Name        string             `json:"name"`

	// SourceType Fund source type (CASH || BANK)
	SourceType FundSourceType `json:"source_type"`
}

// CreateFundSourceResponse defines model for CreateFundSourceResponse.
type CreateFundSourceResponse struct {
	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
}

// CreateTransactionItemRequest defines model for CreateTransactionItemRequest.
type CreateTransactionItemRequest struct {
	Amount      Decimal  `json:"amount"`
	Currency    Currency `json:"currency"`
	Description *string  `json:"description,omitempty"`

	// EntryType Journal entry type (DEBIT || CREDIT)
	EntryType EntryType `json:"entry_type"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid  FundSourceUUID `json:"fund_source_uuid"`
	TransactionDate time.Time      `json:"transaction_date"`

	// WalletUuid UUID of a wallet
	WalletUuid *WalletUUID `json:"wallet_uuid,omitempty"`
}

// CreateTransactionsRequest defines model for CreateTransactionsRequest.
type CreateTransactionsRequest struct {
	Items []CreateTransactionItemRequest `json:"items"`
}

// CreateWalletAllocationRequest defines model for CreateWalletAllocationRequest.
type CreateWalletAllocationRequest struct {
	AllocatedBalance Decimal `json:"allocated_balance"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
}

// CreateWalletRequest defines model for CreateWalletRequest.
type CreateWalletRequest struct {
	Allocations *[]CreateWalletAllocationRequest `json:"allocations,omitempty"`
	Currency    Currency                         `json:"currency"`
	Name        string                           `json:"name"`
}

// CreateWalletResponse defines model for CreateWalletResponse.
type CreateWalletResponse struct {
	// WalletUuid UUID of a wallet
	WalletUuid WalletUUID `json:"wallet_uuid"`
}

// Currency defines model for Currency.
type Currency = shared.Currency

// Decimal defines model for Decimal.
type Decimal = decimal.Decimal

// EntryType Journal entry type (DEBIT || CREDIT)
type EntryType = shared.EntryType

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  string  `json:"error_slug"`
	Message    string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details []ErrorDetails `json:"details"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Error slug
	Slug string `json:"slug"`
}

// FundSourceBankMetadata defines model for FundSourceBankMetadata.
type FundSourceBankMetadata struct {
	AccountNumber string `json:"account_number"`
	AccountOwner  string `json:"account_owner"`
	BankCode      string `json:"bank_code"`
}

// FundSourceBankMetadataResponse defines model for FundSourceBankMetadataResponse.
type FundSourceBankMetadataResponse struct {
	AccountNumber string `json:"account_number"`
	AccountOwner  string `json:"account_owner"`
	BankBin       int    `json:"bank_bin"`
	BankCode      string `json:"bank_code"`
	BankIconUrl   string `json:"bank_icon_url"`
	BankLogoUrl   string `json:"bank_logo_url"`
	BankName      string `json:"bank_name"`
	BankShortName string `json:"bank_short_name"`
}

// FundSourceCashMetadata defines model for FundSourceCashMetadata.
type FundSourceCashMetadata struct {
	OwnerName string `json:"owner_name"`
}

// FundSourceCashMetadataResponse defines model for FundSourceCashMetadataResponse.
type FundSourceCashMetadataResponse struct {
	OwnerName string `json:"owner_name"`
}

// FundSourceMetadata defines model for FundSourceMetadata.
type FundSourceMetadata struct {
	BankMetadata *FundSourceBankMetadata `json:"bank_metadata,omitempty"`
	CashMetadata *FundSourceCashMetadata `json:"cash_metadata,omitempty"`
}

// FundSourceResponse defines model for FundSourceResponse.
type FundSourceResponse struct {
	AvailableBalance Decimal                         `json:"available_balance"`
	Balance          Decimal                         `json:"balance"`
	BankMetadata     *FundSourceBankMetadataResponse `json:"bank_metadata,omitempty"`
	CashMetadata     *FundSourceCashMetadataResponse `json:"cash_metadata,omitempty"`
	Currency         Currency                        `json:"currency"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
	Name           string         `json:"name"`

	// SourceType Fund source type (CASH || BANK)
	SourceType FundSourceType `json:"source_type"`
}

// FundSourceType Fund source type (CASH || BANK)
type FundSourceType = domain.FundSourceType

// FundSourceUUID UUID of a fund source
type FundSourceUUID = domain.FundSourceUUID

// LinkFundSourceAllocationRequest defines model for LinkFundSourceAllocationRequest.
type LinkFundSourceAllocationRequest struct {
	AllocatedAmount Decimal `json:"allocated_amount"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
}

// LinkFundSourcesRequest defines model for LinkFundSourcesRequest.
type LinkFundSourcesRequest struct {
	Allocations []LinkFundSourceAllocationRequest `json:"allocations"`
}

// ListFundSourcesResponse defines model for ListFundSourcesResponse.
type ListFundSourcesResponse struct {
	Items      []FundSourceResponse `json:"items"`
	Pagination Pagination           `json:"pagination"`
}

// ListWalletsResponse defines model for ListWalletsResponse.
type ListWalletsResponse struct {
	Items      []WalletResponse `json:"items"`
	Pagination Pagination       `json:"pagination"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"page_size"`
	Total    int `json:"total"`
}

// WalletAllocationResponse defines model for WalletAllocationResponse.
type WalletAllocationResponse struct {
	Balance        Decimal `json:"balance"`
	FundSourceName string  `json:"fund_source_name"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
}

// WalletResponse defines model for WalletResponse.
type WalletResponse struct {
	Allocations []WalletAllocationResponse `json:"allocations"`
	Balance     Decimal                    `json:"balance"`
	Currency    Currency                   `json:"currency"`
	Name        string                     `json:"name"`

	// WalletUuid UUID of a wallet
	WalletUuid WalletUUID `json:"wallet_uuid"`
}

// WalletUUID UUID of a wallet
type WalletUUID = domain.WalletUUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// ListFundSourcesParams defines parameters for ListFundSources.
type ListFundSourcesParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListWalletsParams defines parameters for ListWallets.
type ListWalletsParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// CreateFundSourceJSONRequestBody defines body for CreateFundSource for application/json ContentType.
type CreateFundSourceJSONRequestBody = CreateFundSourceRequest

// CreateTransactionsJSONRequestBody defines body for CreateTransactions for application/json ContentType.
type CreateTransactionsJSONRequestBody = CreateTransactionsRequest

// CreateWalletJSONRequestBody defines body for CreateWallet for application/json ContentType.
type CreateWalletJSONRequestBody = CreateWalletRequest

// LinkFundSourcesJSONRequestBody defines body for LinkFundSources for application/json ContentType.
type LinkFundSourcesJSONRequestBody = LinkFundSourcesRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListFundSources List all fund sources
	//
	// Corresponds with GET /v1/treasury/fund-sources (the `ListFundSources` operationId).
	ListFundSources(ctx context.Context, params *ListFundSourcesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateFundSourceWithBody Create a new fund source
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/treasury/fund-sources (the `CreateFundSource` operationId).
	CreateFundSourceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateFundSource Create a new fund source
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/treasury/fund-sources (the `CreateFundSource` operationId).
	CreateFundSource(ctx context.Context, body CreateFundSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateTransactionsWithBody Create transactions
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/treasury/transactions (the `CreateTransactions` operationId).
	CreateTransactionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateTransactions Create transactions
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/treasury/transactions (the `CreateTransactions` operationId).
	CreateTransactions(ctx context.Context, body CreateTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListWallets List all wallets
	//
	// Corresponds with GET /v1/treasury/wallets (the `ListWallets` operationId).
	ListWallets(ctx context.Context, params *ListWalletsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateWalletWithBody Create a wallet
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/treasury/wallets (the `CreateWallet` operationId).
	CreateWalletWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateWallet Create a wallet
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/treasury/wallets (the `CreateWallet` operationId).
	CreateWallet(ctx context.Context, body CreateWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LinkFundSourcesWithBody Link fund sources to a wallet
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/treasury/wallets/{wallet_uuid}/fund-sources (the `LinkFundSources` operationId).
	LinkFundSourcesWithBody(ctx context.Context, walletUuid WalletUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LinkFundSources Link fund sources to a wallet
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/treasury/wallets/{wallet_uuid}/fund-sources (the `LinkFundSources` operationId).
	LinkFundSources(ctx context.Context, walletUuid WalletUUID, body LinkFundSourcesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListFundSources List all fund sources
//
// Corresponds with GET /v1/treasury/fund-sources (the `ListFundSources` operationId).
func (c *Client) ListFundSources(ctx context.Context, params *ListFundSourcesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListFundSourcesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateFundSourceWithBody Create a new fund source
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/treasury/fund-sources (the `CreateFundSource` operationId).
func (c *Client) CreateFundSourceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateFundSourceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateFundSource Create a new fund source
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/treasury/fund-sources (the `CreateFundSource` operationId).
func (c *Client) CreateFundSource(ctx context.Context, body CreateFundSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateFundSourceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateTransactionsWithBody Create transactions
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/treasury/transactions (the `CreateTransactions` operationId).
func (c *Client) CreateTransactionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTransactionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateTransactions Create transactions
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/treasury/transactions (the `CreateTransactions` operationId).
func (c *Client) CreateTransactions(ctx context.Context, body CreateTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTransactionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListWallets List all wallets
//
// Corresponds with GET /v1/treasury/wallets (the `ListWallets` operationId).
func (c *Client) ListWallets(ctx context.Context, params *ListWalletsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListWalletsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateWalletWithBody Create a wallet
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/treasury/wallets (the `CreateWallet` operationId).
func (c *Client) CreateWalletWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateWalletRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateWallet Create a wallet
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/treasury/wallets (the `CreateWallet` operationId).
func (c *Client) CreateWallet(ctx context.Context, body CreateWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateWalletRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LinkFundSourcesWithBody Link fund sources to a wallet
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/treasury/wallets/{wallet_uuid}/fund-sources (the `LinkFundSources` operationId).
func (c *Client) LinkFundSourcesWithBody(ctx context.Context, walletUuid WalletUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLinkFundSourcesRequestWithBody(c.Server, walletUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LinkFundSources Link fund sources to a wallet
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/treasury/wallets/{wallet_uuid}/fund-sources (the `LinkFundSources` operationId).
func (c *Client) LinkFundSources(ctx context.Context, walletUuid WalletUUID, body LinkFundSourcesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLinkFundSourcesRequest(c.Server, walletUuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListFundSourcesRequest constructs an http.Request for the ListFundSources method
func NewListFundSourcesRequest(server string, params *ListFundSourcesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/treasury/fund-sources")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_size", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateFundSourceRequest calls the generic CreateFundSource builder with application/json body
func NewCreateFundSourceRequest(server string, body CreateFundSourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateFundSourceRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateFundSourceRequestWithBody constructs an http.Request for the CreateFundSource method, with any body, and a specified content type
func NewCreateFundSourceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/treasury/fund-sources")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateTransactionsRequest calls the generic CreateTransactions builder with application/json body
func NewCreateTransactionsRequest(server string, body CreateTransactionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateTransactionsRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateTransactionsRequestWithBody constructs an http.Request for the CreateTransactions method, with any body, and a specified content type
func NewCreateTransactionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/treasury/transactions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListWalletsRequest constructs an http.Request for the ListWallets method
func NewListWalletsRequest(server string, params *ListWalletsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/treasury/wallets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_size", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateWalletRequest calls the generic CreateWallet builder with application/json body
func NewCreateWalletRequest(server string, body CreateWalletJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateWalletRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateWalletRequestWithBody constructs an http.Request for the CreateWallet method, with any body, and a specified content type
func NewCreateWalletRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/treasury/wallets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewLinkFundSourcesRequest calls the generic LinkFundSources builder with application/json body
func NewLinkFundSourcesRequest(server string, walletUuid WalletUUID, body LinkFundSourcesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLinkFundSourcesRequestWithBody(server, walletUuid, "application/json", bodyReader)
}

// NewLinkFundSourcesRequestWithBody constructs an http.Request for the LinkFundSources method, with any body, and a specified content type
func NewLinkFundSourcesRequestWithBody(server string, walletUuid WalletUUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "wallet_uuid", walletUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/treasury/wallets/%s/fund-sources", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListFundSourcesWithResponse List all fund sources
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/treasury/fund-sources (the `ListFundSources` operationId).
	ListFundSourcesWithResponse(ctx context.Context, params *ListFundSourcesParams, reqEditors ...RequestEditorFn) (*ListFundSourcesClientResponse, error)

	// CreateFundSourceWithBodyWithResponse Create a new fund source
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/treasury/fund-sources (the `CreateFundSource` operationId).
	CreateFundSourceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateFundSourceClientResponse, error)

	// CreateFundSourceWithResponse Create a new fund source
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/treasury/fund-sources (the `CreateFundSource` operationId).
	CreateFundSourceWithResponse(ctx context.Context, body CreateFundSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateFundSourceClientResponse, error)

	// CreateTransactionsWithBodyWithResponse Create transactions
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/treasury/transactions (the `CreateTransactions` operationId).
	CreateTransactionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTransactionsClientResponse, error)

	// CreateTransactionsWithResponse Create transactions
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/treasury/transactions (the `CreateTransactions` operationId).
	CreateTransactionsWithResponse(ctx context.Context, body CreateTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTransactionsClientResponse, error)

	// ListWalletsWithResponse List all wallets
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/treasury/wallets (the `ListWallets` operationId).
	ListWalletsWithResponse(ctx context.Context, params *ListWalletsParams, reqEditors ...RequestEditorFn) (*ListWalletsClientResponse, error)

	// CreateWalletWithBodyWithResponse Create a wallet
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/treasury/wallets (the `CreateWallet` operationId).
	CreateWalletWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateWalletClientResponse, error)

	// CreateWalletWithResponse Create a wallet
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/treasury/wallets (the `CreateWallet` operationId).
	CreateWalletWithResponse(ctx context.Context, body CreateWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateWalletClientResponse, error)

	// LinkFundSourcesWithBodyWithResponse Link fund sources to a wallet
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/treasury/wallets/{wallet_uuid}/fund-sources (the `LinkFundSources` operationId).
	LinkFundSourcesWithBodyWithResponse(ctx context.Context, walletUuid WalletUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LinkFundSourcesClientResponse, error)

	// LinkFundSourcesWithResponse Link fund sources to a wallet
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/treasury/wallets/{wallet_uuid}/fund-sources (the `LinkFundSources` operationId).
	LinkFundSourcesWithResponse(ctx context.Context, walletUuid WalletUUID, body LinkFundSourcesJSONRequestBody, reqEditors ...RequestEditorFn) (*LinkFundSourcesClientResponse, error)
}

type ListFundSourcesClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ListFundSourcesResponse
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListFundSourcesClientResponse) GetJSON200() *ListFundSourcesResponse {
	return r.JSON200
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListFundSourcesClientResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ListFundSourcesClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListFundSourcesClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListFundSourcesClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListFundSourcesClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateFundSourceClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *CreateFundSourceResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateFundSourceClientResponse) GetJSON201() *CreateFundSourceResponse {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateFundSourceClientResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateFundSourceClientResponse) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreateFundSourceClientResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r CreateFundSourceClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateFundSourceClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateFundSourceClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateFundSourceClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateTransactionsClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateTransactionsClientResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreateTransactionsClientResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r CreateTransactionsClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateTransactionsClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateTransactionsClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateTransactionsClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListWalletsClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ListWalletsResponse
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListWalletsClientResponse) GetJSON200() *ListWalletsResponse {
	return r.JSON200
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListWalletsClientResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ListWalletsClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListWalletsClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListWalletsClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListWalletsClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateWalletClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *CreateWalletResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateWalletClientResponse) GetJSON201() *CreateWalletResponse {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateWalletClientResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateWalletClientResponse) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreateWalletClientResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r CreateWalletClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateWalletClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateWalletClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateWalletClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LinkFundSourcesClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r LinkFundSourcesClientResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r LinkFundSourcesClientResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r LinkFundSourcesClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LinkFundSourcesClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LinkFundSourcesClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LinkFundSourcesClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListFundSourcesWithResponse List all fund sources
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/treasury/fund-sources (the `ListFundSources` operationId).
func (c *ClientWithResponses) ListFundSourcesWithResponse(ctx context.Context, params *ListFundSourcesParams, reqEditors ...RequestEditorFn) (*ListFundSourcesClientResponse, error) {
	rsp, err := c.ListFundSources(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListFundSourcesClientResponse(rsp)
}

// CreateFundSourceWithBodyWithResponse Create a new fund source
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/treasury/fund-sources (the `CreateFundSource` operationId).
func (c *ClientWithResponses) CreateFundSourceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateFundSourceClientResponse, error) {
	rsp, err := c.CreateFundSourceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateFundSourceClientResponse(rsp)
}

// CreateFundSourceWithResponse Create a new fund source
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/treasury/fund-sources (the `CreateFundSource` operationId).
func (c *ClientWithResponses) CreateFundSourceWithResponse(ctx context.Context, body CreateFundSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateFundSourceClientResponse, error) {
	rsp, err := c.CreateFundSource(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateFundSourceClientResponse(rsp)
}

// CreateTransactionsWithBodyWithResponse Create transactions
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/treasury/transactions (the `CreateTransactions` operationId).
func (c *ClientWithResponses) CreateTransactionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTransactionsClientResponse, error) {
	rsp, err := c.CreateTransactionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTransactionsClientResponse(rsp)
}

// CreateTransactionsWithResponse Create transactions
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/treasury/transactions (the `CreateTransactions` operationId).
func (c *ClientWithResponses) CreateTransactionsWithResponse(ctx context.Context, body CreateTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTransactionsClientResponse, error) {
	rsp, err := c.CreateTransactions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTransactionsClientResponse(rsp)
}

// ListWalletsWithResponse List all wallets
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/treasury/wallets (the `ListWallets` operationId).
func (c *ClientWithResponses) ListWalletsWithResponse(ctx context.Context, params *ListWalletsParams, reqEditors ...RequestEditorFn) (*ListWalletsClientResponse, error) {
	rsp, err := c.ListWallets(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListWalletsClientResponse(rsp)
}

// CreateWalletWithBodyWithResponse Create a wallet
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/treasury/wallets (the `CreateWallet` operationId).
func (c *ClientWithResponses) CreateWalletWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateWalletClientResponse, error) {
	rsp, err := c.CreateWalletWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateWalletClientResponse(rsp)
}

// CreateWalletWithResponse Create a wallet
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/treasury/wallets (the `CreateWallet` operationId).
func (c *ClientWithResponses) CreateWalletWithResponse(ctx context.Context, body CreateWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateWalletClientResponse, error) {
	rsp, err := c.CreateWallet(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateWalletClientResponse(rsp)
}

// LinkFundSourcesWithBodyWithResponse Link fund sources to a wallet
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/treasury/wallets/{wallet_uuid}/fund-sources (the `LinkFundSources` operationId).
func (c *ClientWithResponses) LinkFundSourcesWithBodyWithResponse(ctx context.Context, walletUuid WalletUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LinkFundSourcesClientResponse, error) {
	rsp, err := c.LinkFundSourcesWithBody(ctx, walletUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLinkFundSourcesClientResponse(rsp)
}

// LinkFundSourcesWithResponse Link fund sources to a wallet
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/treasury/wallets/{wallet_uuid}/fund-sources (the `LinkFundSources` operationId).
func (c *ClientWithResponses) LinkFundSourcesWithResponse(ctx context.Context, walletUuid WalletUUID, body LinkFundSourcesJSONRequestBody, reqEditors ...RequestEditorFn) (*LinkFundSourcesClientResponse, error) {
	rsp, err := c.LinkFundSources(ctx, walletUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLinkFundSourcesClientResponse(rsp)
}

// ParseListFundSourcesClientResponse parses an HTTP response from a ListFundSourcesWithResponse call
func ParseListFundSourcesClientResponse(rsp *http.Response) (*ListFundSourcesClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListFundSourcesClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListFundSourcesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateFundSourceClientResponse parses an HTTP response from a CreateFundSourceWithResponse call
func ParseCreateFundSourceClientResponse(rsp *http.Response) (*CreateFundSourceClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateFundSourceClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateFundSourceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateTransactionsClientResponse parses an HTTP response from a CreateTransactionsWithResponse call
func ParseCreateTransactionsClientResponse(rsp *http.Response) (*CreateTransactionsClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateTransactionsClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListWalletsClientResponse parses an HTTP response from a ListWalletsWithResponse call
func ParseListWalletsClientResponse(rsp *http.Response) (*ListWalletsClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListWalletsClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListWalletsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateWalletClientResponse parses an HTTP response from a CreateWalletWithResponse call
func ParseCreateWalletClientResponse(rsp *http.Response) (*CreateWalletClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateWalletClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateWalletResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseLinkFundSourcesClientResponse parses an HTTP response from a LinkFundSourcesWithResponse call
func ParseLinkFundSourcesClientResponse(rsp *http.Response) (*LinkFundSourcesClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LinkFundSourcesClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
