// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"

	"github.com/oapi-codegen/runtime"
	"github.com/shopspring/decimal"
)

// Currency defines model for Currency.
type Currency = shared.Currency

// Decimal defines model for Decimal.
type Decimal = decimal.Decimal

// EntryType Journal entry type (DEBIT || CREDIT)
type EntryType = shared.EntryType

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  string  `json:"error_slug"`
	Message    string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details []ErrorDetails `json:"details"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Error slug
	Slug string `json:"slug"`
}

// FundSourceBankMetadata defines model for FundSourceBankMetadata.
type FundSourceBankMetadata struct {
	AccountNumber string `json:"account_number"`
	AccountOwner  string `json:"account_owner"`
	BankCode      string `json:"bank_code"`
}

// FundSourceCashMetadata defines model for FundSourceCashMetadata.
type FundSourceCashMetadata struct {
	OwnerName string `json:"owner_name"`
}

// FundSourceMetadata defines model for FundSourceMetadata.
type FundSourceMetadata struct {
	BankMetadata *FundSourceBankMetadata `json:"bank_metadata,omitempty"`
	CashMetadata *FundSourceCashMetadata `json:"cash_metadata,omitempty"`
}

// FundSourceType Fund source type (CASH || BANK)
type FundSourceType = domain.FundSourceType

// FundSourceUUID UUID of a fund source
type FundSourceUUID = domain.FundSourceUUID

// JournalEntryItem defines model for JournalEntryItem.
type JournalEntryItem struct {
	Amount      Decimal `json:"amount"`
	Description *string `json:"description,omitempty"`

	// EntryType Journal entry type (DEBIT || CREDIT)
	EntryType       EntryType `json:"entry_type"`
	TransactionDate time.Time `json:"transaction_date"`
	TransactionNo   *string   `json:"transaction_no,omitempty"`
}

// JournalEntryResponse defines model for JournalEntryResponse.
type JournalEntryResponse struct {
	Amount        Decimal   `json:"amount"`
	BalanceAfter  Decimal   `json:"balance_after"`
	BalanceBefore Decimal   `json:"balance_before"`
	CreatedAt     time.Time `json:"created_at"`
	CreatedBy     string    `json:"created_by"`
	Description   *string   `json:"description,omitempty"`

	// EntryType Journal entry type (DEBIT || CREDIT)
	EntryType EntryType `json:"entry_type"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`

	// JournalEntryUuid UUID of a journal entry
	JournalEntryUuid JournalEntryUUID `json:"journal_entry_uuid"`

	// ReverseEntryUuid UUID of a journal entry
	ReverseEntryUuid *JournalEntryUUID `json:"reverse_entry_uuid,omitempty"`

	// Status Journal entry status (RECORDED || POSTED || VOIDED)
	Status          JournalEntryStatus `json:"status"`
	TransactionDate time.Time          `json:"transaction_date"`
	TransactionNo   *string            `json:"transaction_no,omitempty"`
	UpdatedAt       *time.Time         `json:"updated_at,omitempty"`
	UpdatedBy       *string            `json:"updated_by,omitempty"`
	VoidedAt        *time.Time         `json:"voided_at,omitempty"`
	VoidedBy        *string            `json:"voided_by,omitempty"`
	VoidedReason    *string            `json:"voided_reason,omitempty"`
}

// JournalEntryStatus Journal entry status (RECORDED || POSTED || VOIDED)
type JournalEntryStatus = domain.JournalEntryStatus

// JournalEntryUUID UUID of a journal entry
type JournalEntryUUID = domain.JournalEntryUUID

// RecordJournalEntriesRequest defines model for RecordJournalEntriesRequest.
type RecordJournalEntriesRequest = []JournalEntryItem

// RecordJournalEntriesResponse defines model for RecordJournalEntriesResponse.
type RecordJournalEntriesResponse = map[string]interface{}

// RegisterFundSourceRequest defines model for RegisterFundSourceRequest.
type RegisterFundSourceRequest struct {
	Currency    Currency           `json:"currency"`
	InitBalance Decimal            `json:"init_balance"`
	Metadata    FundSourceMetadata `json:"metadata"`
	Name        string             `json:"name"`

	// SourceType Fund source type (CASH || BANK)
	SourceType FundSourceType `json:"source_type"`
}

// RegisterFundSourceResponse defines model for RegisterFundSourceResponse.
type RegisterFundSourceResponse struct {
	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
}

// VoidJournalEntryRequest defines model for VoidJournalEntryRequest.
type VoidJournalEntryRequest struct {
	VoidReason string `json:"void_reason"`
}

// VoidJournalEntryResponse defines model for VoidJournalEntryResponse.
type VoidJournalEntryResponse struct {
	ReverseJournalEntry JournalEntryResponse `json:"reverse_journal_entry"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// RegisterFundSourceJSONRequestBody defines body for RegisterFundSource for application/json ContentType.
type RegisterFundSourceJSONRequestBody = RegisterFundSourceRequest

// RecordJournalEntriesJSONRequestBody defines body for RecordJournalEntries for application/json ContentType.
type RecordJournalEntriesJSONRequestBody = RecordJournalEntriesRequest

// VoidJournalEntryJSONRequestBody defines body for VoidJournalEntry for application/json ContentType.
type VoidJournalEntryJSONRequestBody = VoidJournalEntryRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RegisterFundSourceWithBody request with any body
	RegisterFundSourceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RegisterFundSource(ctx context.Context, body RegisterFundSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RecordJournalEntriesWithBody request with any body
	RecordJournalEntriesWithBody(ctx context.Context, fundSourceUuid FundSourceUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RecordJournalEntries(ctx context.Context, fundSourceUuid FundSourceUUID, body RecordJournalEntriesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VoidJournalEntryWithBody request with any body
	VoidJournalEntryWithBody(ctx context.Context, fundSourceUuid FundSourceUUID, journalEntryUuid JournalEntryUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	VoidJournalEntry(ctx context.Context, fundSourceUuid FundSourceUUID, journalEntryUuid JournalEntryUUID, body VoidJournalEntryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RegisterFundSourceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterFundSourceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterFundSource(ctx context.Context, body RegisterFundSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterFundSourceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecordJournalEntriesWithBody(ctx context.Context, fundSourceUuid FundSourceUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecordJournalEntriesRequestWithBody(c.Server, fundSourceUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecordJournalEntries(ctx context.Context, fundSourceUuid FundSourceUUID, body RecordJournalEntriesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecordJournalEntriesRequest(c.Server, fundSourceUuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VoidJournalEntryWithBody(ctx context.Context, fundSourceUuid FundSourceUUID, journalEntryUuid JournalEntryUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVoidJournalEntryRequestWithBody(c.Server, fundSourceUuid, journalEntryUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VoidJournalEntry(ctx context.Context, fundSourceUuid FundSourceUUID, journalEntryUuid JournalEntryUUID, body VoidJournalEntryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVoidJournalEntryRequest(c.Server, fundSourceUuid, journalEntryUuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRegisterFundSourceRequest calls the generic RegisterFundSource builder with application/json body
func NewRegisterFundSourceRequest(server string, body RegisterFundSourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterFundSourceRequestWithBody(server, "application/json", bodyReader)
}

// NewRegisterFundSourceRequestWithBody generates requests for RegisterFundSource with any type of body
func NewRegisterFundSourceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/treasury/fund-sources")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRecordJournalEntriesRequest calls the generic RecordJournalEntries builder with application/json body
func NewRecordJournalEntriesRequest(server string, fundSourceUuid FundSourceUUID, body RecordJournalEntriesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRecordJournalEntriesRequestWithBody(server, fundSourceUuid, "application/json", bodyReader)
}

// NewRecordJournalEntriesRequestWithBody generates requests for RecordJournalEntries with any type of body
func NewRecordJournalEntriesRequestWithBody(server string, fundSourceUuid FundSourceUUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "fund_source_uuid", fundSourceUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/treasury/fund-sources/%s/journal-entries", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewVoidJournalEntryRequest calls the generic VoidJournalEntry builder with application/json body
func NewVoidJournalEntryRequest(server string, fundSourceUuid FundSourceUUID, journalEntryUuid JournalEntryUUID, body VoidJournalEntryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewVoidJournalEntryRequestWithBody(server, fundSourceUuid, journalEntryUuid, "application/json", bodyReader)
}

// NewVoidJournalEntryRequestWithBody generates requests for VoidJournalEntry with any type of body
func NewVoidJournalEntryRequestWithBody(server string, fundSourceUuid FundSourceUUID, journalEntryUuid JournalEntryUUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "fund_source_uuid", fundSourceUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "journal_entry_uuid", journalEntryUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/treasury/fund-sources/%s/journal-entries/%s/void", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RegisterFundSourceWithBodyWithResponse request with any body
	RegisterFundSourceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterFundSourceClientResponse, error)

	RegisterFundSourceWithResponse(ctx context.Context, body RegisterFundSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterFundSourceClientResponse, error)

	// RecordJournalEntriesWithBodyWithResponse request with any body
	RecordJournalEntriesWithBodyWithResponse(ctx context.Context, fundSourceUuid FundSourceUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecordJournalEntriesClientResponse, error)

	RecordJournalEntriesWithResponse(ctx context.Context, fundSourceUuid FundSourceUUID, body RecordJournalEntriesJSONRequestBody, reqEditors ...RequestEditorFn) (*RecordJournalEntriesClientResponse, error)

	// VoidJournalEntryWithBodyWithResponse request with any body
	VoidJournalEntryWithBodyWithResponse(ctx context.Context, fundSourceUuid FundSourceUUID, journalEntryUuid JournalEntryUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VoidJournalEntryClientResponse, error)

	VoidJournalEntryWithResponse(ctx context.Context, fundSourceUuid FundSourceUUID, journalEntryUuid JournalEntryUUID, body VoidJournalEntryJSONRequestBody, reqEditors ...RequestEditorFn) (*VoidJournalEntryClientResponse, error)
}

type RegisterFundSourceClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RegisterFundSourceResponse
	JSON400      *BadRequest
	JSON409      *ErrorResponse
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r RegisterFundSourceClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterFundSourceClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RecordJournalEntriesClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RecordJournalEntriesResponse
	JSON400      *BadRequest
	JSON404      *NotFound
	JSON409      *ErrorResponse
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r RecordJournalEntriesClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RecordJournalEntriesClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VoidJournalEntryClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VoidJournalEntryResponse
	JSON400      *BadRequest
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r VoidJournalEntryClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VoidJournalEntryClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RegisterFundSourceWithBodyWithResponse request with arbitrary body returning *RegisterFundSourceClientResponse
func (c *ClientWithResponses) RegisterFundSourceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterFundSourceClientResponse, error) {
	rsp, err := c.RegisterFundSourceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterFundSourceClientResponse(rsp)
}

func (c *ClientWithResponses) RegisterFundSourceWithResponse(ctx context.Context, body RegisterFundSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterFundSourceClientResponse, error) {
	rsp, err := c.RegisterFundSource(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterFundSourceClientResponse(rsp)
}

// RecordJournalEntriesWithBodyWithResponse request with arbitrary body returning *RecordJournalEntriesClientResponse
func (c *ClientWithResponses) RecordJournalEntriesWithBodyWithResponse(ctx context.Context, fundSourceUuid FundSourceUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecordJournalEntriesClientResponse, error) {
	rsp, err := c.RecordJournalEntriesWithBody(ctx, fundSourceUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecordJournalEntriesClientResponse(rsp)
}

func (c *ClientWithResponses) RecordJournalEntriesWithResponse(ctx context.Context, fundSourceUuid FundSourceUUID, body RecordJournalEntriesJSONRequestBody, reqEditors ...RequestEditorFn) (*RecordJournalEntriesClientResponse, error) {
	rsp, err := c.RecordJournalEntries(ctx, fundSourceUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecordJournalEntriesClientResponse(rsp)
}

// VoidJournalEntryWithBodyWithResponse request with arbitrary body returning *VoidJournalEntryClientResponse
func (c *ClientWithResponses) VoidJournalEntryWithBodyWithResponse(ctx context.Context, fundSourceUuid FundSourceUUID, journalEntryUuid JournalEntryUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VoidJournalEntryClientResponse, error) {
	rsp, err := c.VoidJournalEntryWithBody(ctx, fundSourceUuid, journalEntryUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVoidJournalEntryClientResponse(rsp)
}

func (c *ClientWithResponses) VoidJournalEntryWithResponse(ctx context.Context, fundSourceUuid FundSourceUUID, journalEntryUuid JournalEntryUUID, body VoidJournalEntryJSONRequestBody, reqEditors ...RequestEditorFn) (*VoidJournalEntryClientResponse, error) {
	rsp, err := c.VoidJournalEntry(ctx, fundSourceUuid, journalEntryUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVoidJournalEntryClientResponse(rsp)
}

// ParseRegisterFundSourceClientResponse parses an HTTP response from a RegisterFundSourceWithResponse call
func ParseRegisterFundSourceClientResponse(rsp *http.Response) (*RegisterFundSourceClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterFundSourceClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RegisterFundSourceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRecordJournalEntriesClientResponse parses an HTTP response from a RecordJournalEntriesWithResponse call
func ParseRecordJournalEntriesClientResponse(rsp *http.Response) (*RecordJournalEntriesClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RecordJournalEntriesClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RecordJournalEntriesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseVoidJournalEntryClientResponse parses an HTTP response from a VoidJournalEntryWithResponse call
func ParseVoidJournalEntryClientResponse(rsp *http.Response) (*VoidJournalEntryClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VoidJournalEntryClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VoidJournalEntryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
