// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/finance/app/models"
	"sumni-finance-backend/internal/finance/domain"
)

type FinancesFundProviderType string

const (
	FinancesFundProviderTypeBank FinancesFundProviderType = "bank"
	FinancesFundProviderTypeCash FinancesFundProviderType = "cash"
)

func (e *FinancesFundProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FinancesFundProviderType(s)
	case string:
		*e = FinancesFundProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for FinancesFundProviderType: %T", src)
	}
	return nil
}

type NullFinancesFundProviderType struct {
	FinancesFundProviderType FinancesFundProviderType
	Valid                    bool // Valid is true if FinancesFundProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFinancesFundProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.FinancesFundProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FinancesFundProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFinancesFundProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FinancesFundProviderType), nil
}

type FinancesFundProvider struct {
	FundProviderUuid  domain.FundProviderUUID
	Name              string
	Balance           decimal.Decimal
	AvailableBalance  decimal.Decimal
	Currency          shared.Currency
	FundProviderType  domain.FundProviderType
	BankName          *string
	BankAccountNumber *string
	BankAccountOwner  *string
	CashOwnerName     *string
	OfficeUuid        models.OfficeUUID
}

type FinancesOffice struct {
	OfficeUuid models.OfficeUUID
	Name       string
}

type FinancesWallet struct {
	WalletUuid  domain.WalletUUID
	Name        string
	Description string
	Balance     pgtype.Numeric
	Currency    shared.Currency
	OfficeUuid  models.OfficeUUID
}

type FinancesWalletAllocation struct {
	WalletUuid       domain.WalletUUID
	FundProviderUuid domain.FundProviderUUID
	AllocationAmount pgtype.Numeric
}
