// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offices.sql

package dbmodels

import (
	"context"

	"sumni-finance-backend/internal/finance/app/models"
)

const officeByUUID = `-- name: OfficeByUUID :one
SELECT office_uuid, name
FROM finances.offices
WHERE office_uuid = $1
`

func (q *Queries) OfficeByUUID(ctx context.Context, officeUuid models.OfficeUUID) (FinancesOffice, error) {
	row := q.db.QueryRow(ctx, officeByUUID, officeUuid)
	var i FinancesOffice
	err := row.Scan(&i.OfficeUuid, &i.Name)
	return i, err
}

const upsertOffice = `-- name: UpsertOffice :exec
INSERT INTO finances.offices (office_uuid, name)
VALUES 
    ($1, $2)
ON CONFLICT (office_uuid) DO
UPDATE SET
    name = EXCLUDED.name
`

type UpsertOfficeParams struct {
	OfficeUuid models.OfficeUUID
	Name       string
}

func (q *Queries) UpsertOffice(ctx context.Context, arg UpsertOfficeParams) error {
	_, err := q.db.Exec(ctx, upsertOffice, arg.OfficeUuid, arg.Name)
	return err
}
