// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package dbmodels

import (
	"context"

	"sumni-finance-backend/internal/finance/domain"
)

const walletByUUID = `-- name: WalletByUUID :one
SELECT wallet_uuid, name, description, balance, currency, office_uuid
FROM finances.wallets
WHERE wallet_uuid = $1
`

func (q *Queries) WalletByUUID(ctx context.Context, walletUuid domain.WalletUUID) (FinancesWallet, error) {
	row := q.db.QueryRow(ctx, walletByUUID, walletUuid)
	var i FinancesWallet
	err := row.Scan(
		&i.WalletUuid,
		&i.Name,
		&i.Description,
		&i.Balance,
		&i.Currency,
		&i.OfficeUuid,
	)
	return i, err
}
