// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	"github.com/shopspring/decimal"
)

// CreateFundSourceRequest defines model for CreateFundSourceRequest.
type CreateFundSourceRequest struct {
	Currency    Currency           `json:"currency"`
	InitBalance Decimal            `json:"init_balance"`
	Metadata    FundSourceMetadata `json:"metadata"`
	Name        string             `json:"name"`

	// SourceType Fund source type (CASH || BANK)
	SourceType FundSourceType `json:"source_type"`
}

// CreateFundSourceResponse defines model for CreateFundSourceResponse.
type CreateFundSourceResponse struct {
	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
}

// CreateTransactionItemRequest defines model for CreateTransactionItemRequest.
type CreateTransactionItemRequest struct {
	Amount      Decimal  `json:"amount"`
	Currency    Currency `json:"currency"`
	Description *string  `json:"description,omitempty"`

	// EntryType Journal entry type (DEBIT || CREDIT)
	EntryType EntryType `json:"entry_type"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid  FundSourceUUID `json:"fund_source_uuid"`
	TransactionDate time.Time      `json:"transaction_date"`

	// WalletUuid UUID of a wallet
	WalletUuid *WalletUUID `json:"wallet_uuid,omitempty"`
}

// CreateTransactionsRequest defines model for CreateTransactionsRequest.
type CreateTransactionsRequest struct {
	Items []CreateTransactionItemRequest `json:"items"`
}

// CreateWalletAllocationRequest defines model for CreateWalletAllocationRequest.
type CreateWalletAllocationRequest struct {
	AllocatedBalance Decimal `json:"allocated_balance"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
}

// CreateWalletRequest defines model for CreateWalletRequest.
type CreateWalletRequest struct {
	Allocations *[]CreateWalletAllocationRequest `json:"allocations,omitempty"`
	Currency    Currency                         `json:"currency"`
	Name        string                           `json:"name"`
}

// CreateWalletResponse defines model for CreateWalletResponse.
type CreateWalletResponse struct {
	// WalletUuid UUID of a wallet
	WalletUuid WalletUUID `json:"wallet_uuid"`
}

// Currency defines model for Currency.
type Currency = shared.Currency

// Decimal defines model for Decimal.
type Decimal = decimal.Decimal

// EntryType Journal entry type (DEBIT || CREDIT)
type EntryType = shared.EntryType

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  string  `json:"error_slug"`
	Message    string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details []ErrorDetails `json:"details"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Error slug
	Slug string `json:"slug"`
}

// FundSourceBankMetadata defines model for FundSourceBankMetadata.
type FundSourceBankMetadata struct {
	AccountNumber string `json:"account_number"`
	AccountOwner  string `json:"account_owner"`
	BankCode      string `json:"bank_code"`
}

// FundSourceBankMetadataResponse defines model for FundSourceBankMetadataResponse.
type FundSourceBankMetadataResponse struct {
	AccountNumber string `json:"account_number"`
	AccountOwner  string `json:"account_owner"`
	BankBin       int    `json:"bank_bin"`
	BankCode      string `json:"bank_code"`
	BankIconUrl   string `json:"bank_icon_url"`
	BankLogoUrl   string `json:"bank_logo_url"`
	BankName      string `json:"bank_name"`
	BankShortName string `json:"bank_short_name"`
}

// FundSourceCashMetadata defines model for FundSourceCashMetadata.
type FundSourceCashMetadata struct {
	OwnerName string `json:"owner_name"`
}

// FundSourceCashMetadataResponse defines model for FundSourceCashMetadataResponse.
type FundSourceCashMetadataResponse struct {
	OwnerName string `json:"owner_name"`
}

// FundSourceMetadata defines model for FundSourceMetadata.
type FundSourceMetadata struct {
	BankMetadata *FundSourceBankMetadata `json:"bank_metadata,omitempty"`
	CashMetadata *FundSourceCashMetadata `json:"cash_metadata,omitempty"`
}

// FundSourceResponse defines model for FundSourceResponse.
type FundSourceResponse struct {
	AvailableBalance Decimal                         `json:"available_balance"`
	Balance          Decimal                         `json:"balance"`
	BankMetadata     *FundSourceBankMetadataResponse `json:"bank_metadata,omitempty"`
	CashMetadata     *FundSourceCashMetadataResponse `json:"cash_metadata,omitempty"`
	Currency         Currency                        `json:"currency"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
	Name           string         `json:"name"`

	// SourceType Fund source type (CASH || BANK)
	SourceType FundSourceType `json:"source_type"`
}

// FundSourceType Fund source type (CASH || BANK)
type FundSourceType = domain.FundSourceType

// FundSourceUUID UUID of a fund source
type FundSourceUUID = domain.FundSourceUUID

// LinkFundSourceAllocationRequest defines model for LinkFundSourceAllocationRequest.
type LinkFundSourceAllocationRequest struct {
	AllocatedAmount Decimal `json:"allocated_amount"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
}

// LinkFundSourcesRequest defines model for LinkFundSourcesRequest.
type LinkFundSourcesRequest struct {
	Allocations []LinkFundSourceAllocationRequest `json:"allocations"`
}

// ListFundSourcesResponse defines model for ListFundSourcesResponse.
type ListFundSourcesResponse struct {
	Items      []FundSourceResponse `json:"items"`
	Pagination Pagination           `json:"pagination"`
}

// ListWalletsResponse defines model for ListWalletsResponse.
type ListWalletsResponse struct {
	Items      []WalletResponse `json:"items"`
	Pagination Pagination       `json:"pagination"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"page_size"`
	Total    int `json:"total"`
}

// WalletAllocationResponse defines model for WalletAllocationResponse.
type WalletAllocationResponse struct {
	Balance        Decimal `json:"balance"`
	FundSourceName string  `json:"fund_source_name"`

	// FundSourceUuid UUID of a fund source
	FundSourceUuid FundSourceUUID `json:"fund_source_uuid"`
}

// WalletResponse defines model for WalletResponse.
type WalletResponse struct {
	Allocations []WalletAllocationResponse `json:"allocations"`
	Balance     Decimal                    `json:"balance"`
	Currency    Currency                   `json:"currency"`
	Name        string                     `json:"name"`

	// WalletUuid UUID of a wallet
	WalletUuid WalletUUID `json:"wallet_uuid"`
}

// WalletUUID UUID of a wallet
type WalletUUID = domain.WalletUUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// ListFundSourcesParams defines parameters for ListFundSources.
type ListFundSourcesParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListWalletsParams defines parameters for ListWallets.
type ListWalletsParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// CreateFundSourceJSONRequestBody defines body for CreateFundSource for application/json ContentType.
type CreateFundSourceJSONRequestBody = CreateFundSourceRequest

// CreateTransactionsJSONRequestBody defines body for CreateTransactions for application/json ContentType.
type CreateTransactionsJSONRequestBody = CreateTransactionsRequest

// CreateWalletJSONRequestBody defines body for CreateWallet for application/json ContentType.
type CreateWalletJSONRequestBody = CreateWalletRequest

// LinkFundSourcesJSONRequestBody defines body for LinkFundSources for application/json ContentType.
type LinkFundSourcesJSONRequestBody = LinkFundSourcesRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListFundSources List all fund sources
	// (GET /v1/treasury/fund-sources)
	ListFundSources(ctx *echo.Context, params ListFundSourcesParams) error
	// CreateFundSource Create a new fund source
	// (POST /v1/treasury/fund-sources)
	CreateFundSource(ctx *echo.Context) error
	// CreateTransactions Create transactions
	// (POST /v1/treasury/transactions)
	CreateTransactions(ctx *echo.Context) error
	// ListWallets List all wallets
	// (GET /v1/treasury/wallets)
	ListWallets(ctx *echo.Context, params ListWalletsParams) error
	// CreateWallet Create a wallet
	// (POST /v1/treasury/wallets)
	CreateWallet(ctx *echo.Context) error
	// LinkFundSources Link fund sources to a wallet
	// (POST /v1/treasury/wallets/{wallet_uuid}/fund-sources)
	LinkFundSources(ctx *echo.Context, walletUuid WalletUUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListFundSources converts echo context to params.
func (w *ServerInterfaceWrapper) ListFundSources(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFundSourcesParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListFundSources(ctx, params)
	return err
}

// CreateFundSource converts echo context to params.
func (w *ServerInterfaceWrapper) CreateFundSource(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateFundSource(ctx)
	return err
}

// CreateTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTransactions(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTransactions(ctx)
	return err
}

// ListWallets converts echo context to params.
func (w *ServerInterfaceWrapper) ListWallets(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWalletsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListWallets(ctx, params)
	return err
}

// CreateWallet converts echo context to params.
func (w *ServerInterfaceWrapper) CreateWallet(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateWallet(ctx)
	return err
}

// LinkFundSources converts echo context to params.
func (w *ServerInterfaceWrapper) LinkFundSources(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "wallet_uuid" -------------
	var walletUuid WalletUUID

	err = runtime.BindStyledParameterWithOptions("simple", "wallet_uuid", ctx.Param("wallet_uuid"), &walletUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter wallet_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LinkFundSources(ctx, walletUuid)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/v1/treasury/fund-sources", wrapper.ListFundSources, options.OperationMiddlewares["listFundSources"]...)
	router.POST(options.BaseURL+"/v1/treasury/fund-sources", wrapper.CreateFundSource, options.OperationMiddlewares["createFundSource"]...)
	router.GET(options.BaseURL+"/v1/treasury/wallets", wrapper.ListWallets, options.OperationMiddlewares["listWallets"]...)
	router.POST(options.BaseURL+"/v1/treasury/wallets", wrapper.CreateWallet, options.OperationMiddlewares["createWallet"]...)
	router.POST(options.BaseURL+"/v1/treasury/wallets/:wallet_uuid/fund-sources", wrapper.LinkFundSources, options.OperationMiddlewares["linkFundSources"]...)
	router.POST(options.BaseURL+"/v1/treasury/transactions", wrapper.CreateTransactions, options.OperationMiddlewares["createTransactions"]...)

}

type BadRequestJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type ListFundSourcesRequestObject struct {
	Params ListFundSourcesParams
}

type ListFundSourcesResponseObject interface {
	VisitListFundSourcesResponse(w http.ResponseWriter) error
}

type ListFundSources200JSONResponse ListFundSourcesResponse

func (response ListFundSources200JSONResponse) VisitListFundSourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListFundSources500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListFundSources500JSONResponse) VisitListFundSourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateFundSourceRequestObject struct {
	Body *CreateFundSourceJSONRequestBody
}

type CreateFundSourceResponseObject interface {
	VisitCreateFundSourceResponse(w http.ResponseWriter) error
}

type CreateFundSource201JSONResponse CreateFundSourceResponse

func (response CreateFundSource201JSONResponse) VisitCreateFundSourceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateFundSource400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateFundSource400JSONResponse) VisitCreateFundSourceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateFundSource409JSONResponse ErrorResponse

func (response CreateFundSource409JSONResponse) VisitCreateFundSourceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateFundSource500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateFundSource500JSONResponse) VisitCreateFundSourceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTransactionsRequestObject struct {
	Body *CreateTransactionsJSONRequestBody
}

type CreateTransactionsResponseObject interface {
	VisitCreateTransactionsResponse(w http.ResponseWriter) error
}

type CreateTransactions204Response struct {
}

func (response CreateTransactions204Response) VisitCreateTransactionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CreateTransactions400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateTransactions400JSONResponse) VisitCreateTransactionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTransactions500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateTransactions500JSONResponse) VisitCreateTransactionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListWalletsRequestObject struct {
	Params ListWalletsParams
}

type ListWalletsResponseObject interface {
	VisitListWalletsResponse(w http.ResponseWriter) error
}

type ListWallets200JSONResponse ListWalletsResponse

func (response ListWallets200JSONResponse) VisitListWalletsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListWallets500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListWallets500JSONResponse) VisitListWalletsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWalletRequestObject struct {
	Body *CreateWalletJSONRequestBody
}

type CreateWalletResponseObject interface {
	VisitCreateWalletResponse(w http.ResponseWriter) error
}

type CreateWallet201JSONResponse CreateWalletResponse

func (response CreateWallet201JSONResponse) VisitCreateWalletResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWallet400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateWallet400JSONResponse) VisitCreateWalletResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWallet409JSONResponse ErrorResponse

func (response CreateWallet409JSONResponse) VisitCreateWalletResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWallet500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateWallet500JSONResponse) VisitCreateWalletResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LinkFundSourcesRequestObject struct {
	WalletUuid WalletUUID `json:"wallet_uuid"`
	Body       *LinkFundSourcesJSONRequestBody
}

type LinkFundSourcesResponseObject interface {
	VisitLinkFundSourcesResponse(w http.ResponseWriter) error
}

type LinkFundSources204Response struct {
}

func (response LinkFundSources204Response) VisitLinkFundSourcesResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LinkFundSources400JSONResponse struct{ BadRequestJSONResponse }

func (response LinkFundSources400JSONResponse) VisitLinkFundSourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LinkFundSources500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response LinkFundSources500JSONResponse) VisitLinkFundSourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListFundSources List all fund sources
	// (GET /v1/treasury/fund-sources)
	ListFundSources(ctx context.Context, request ListFundSourcesRequestObject) (ListFundSourcesResponseObject, error)
	// CreateFundSource Create a new fund source
	// (POST /v1/treasury/fund-sources)
	CreateFundSource(ctx context.Context, request CreateFundSourceRequestObject) (CreateFundSourceResponseObject, error)
	// CreateTransactions Create transactions
	// (POST /v1/treasury/transactions)
	CreateTransactions(ctx context.Context, request CreateTransactionsRequestObject) (CreateTransactionsResponseObject, error)
	// ListWallets List all wallets
	// (GET /v1/treasury/wallets)
	ListWallets(ctx context.Context, request ListWalletsRequestObject) (ListWalletsResponseObject, error)
	// CreateWallet Create a wallet
	// (POST /v1/treasury/wallets)
	CreateWallet(ctx context.Context, request CreateWalletRequestObject) (CreateWalletResponseObject, error)
	// LinkFundSources Link fund sources to a wallet
	// (POST /v1/treasury/wallets/{wallet_uuid}/fund-sources)
	LinkFundSources(ctx context.Context, request LinkFundSourcesRequestObject) (LinkFundSourcesResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListFundSources operation middleware
func (sh *strictHandler) ListFundSources(ctx *echo.Context, params ListFundSourcesParams) error {
	var request ListFundSourcesRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListFundSources(ctx.Request().Context(), request.(ListFundSourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFundSources")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListFundSourcesResponseObject); ok {
		return validResponse.VisitListFundSourcesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateFundSource operation middleware
func (sh *strictHandler) CreateFundSource(ctx *echo.Context) error {
	var request CreateFundSourceRequestObject

	var body CreateFundSourceJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateFundSource(ctx.Request().Context(), request.(CreateFundSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateFundSource")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateFundSourceResponseObject); ok {
		return validResponse.VisitCreateFundSourceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTransactions operation middleware
func (sh *strictHandler) CreateTransactions(ctx *echo.Context) error {
	var request CreateTransactionsRequestObject

	var body CreateTransactionsJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTransactions(ctx.Request().Context(), request.(CreateTransactionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTransactions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTransactionsResponseObject); ok {
		return validResponse.VisitCreateTransactionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListWallets operation middleware
func (sh *strictHandler) ListWallets(ctx *echo.Context, params ListWalletsParams) error {
	var request ListWalletsRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListWallets(ctx.Request().Context(), request.(ListWalletsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWallets")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListWalletsResponseObject); ok {
		return validResponse.VisitListWalletsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateWallet operation middleware
func (sh *strictHandler) CreateWallet(ctx *echo.Context) error {
	var request CreateWalletRequestObject

	var body CreateWalletJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWallet(ctx.Request().Context(), request.(CreateWalletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWallet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateWalletResponseObject); ok {
		return validResponse.VisitCreateWalletResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LinkFundSources operation middleware
func (sh *strictHandler) LinkFundSources(ctx *echo.Context, walletUuid WalletUUID) error {
	var request LinkFundSourcesRequestObject

	request.WalletUuid = walletUuid

	var body LinkFundSourcesJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LinkFundSources(ctx.Request().Context(), request.(LinkFundSourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LinkFundSources")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LinkFundSourcesResponseObject); ok {
		return validResponse.VisitLinkFundSourcesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
