// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package dbmodels

import (
	"context"
)

// iteratorForCreateWalletAllocations implements pgx.CopyFromSource.
type iteratorForCreateWalletAllocations struct {
	rows                 []CreateWalletAllocationsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateWalletAllocations) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateWalletAllocations) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].WalletUuid,
		r.rows[0].FundSourceUuid,
		r.rows[0].Balance,
	}, nil
}

func (r iteratorForCreateWalletAllocations) Err() error {
	return nil
}

func (q *Queries) CreateWalletAllocations(ctx context.Context, arg []CreateWalletAllocationsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"treasury", "wallet_allocations"}, []string{"wallet_uuid", "fund_source_uuid", "balance"}, &iteratorForCreateWalletAllocations{rows: arg})
}
