// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package dbmodels

import (
	"context"
)

// iteratorForBatchInsertJournalEntries implements pgx.CopyFromSource.
type iteratorForBatchInsertJournalEntries struct {
	rows                 []BatchInsertJournalEntriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertJournalEntries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertJournalEntries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].JournalEntryUuid,
		r.rows[0].FundSourceUuid,
		r.rows[0].Amount,
		r.rows[0].EntryType,
		r.rows[0].BalanceBefore,
		r.rows[0].BalanceAfter,
		r.rows[0].Status,
		r.rows[0].TransactionDate,
		r.rows[0].TransactionNo,
		r.rows[0].Description,
		r.rows[0].CreatedAt,
		r.rows[0].CreatedBy,
	}, nil
}

func (r iteratorForBatchInsertJournalEntries) Err() error {
	return nil
}

func (q *Queries) BatchInsertJournalEntries(ctx context.Context, arg []BatchInsertJournalEntriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"treasury", "journal_entries"}, []string{"journal_entry_uuid", "fund_source_uuid", "amount", "entry_type", "balance_before", "balance_after", "status", "transaction_date", "transaction_no", "description", "created_at", "created_by"}, &iteratorForBatchInsertJournalEntries{rows: arg})
}
