// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fund_sources.sql

package dbmodels

import (
	"context"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"
)

const countFundSources = `-- name: CountFundSources :one
SELECT COUNT(*)
FROM treasury.fund_sources
WHERE tenant_id = $1
  AND office_id = $2
`

type CountFundSourcesParams struct {
	TenantID string
	OfficeID string
}

func (q *Queries) CountFundSources(ctx context.Context, arg CountFundSourcesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFundSources, arg.TenantID, arg.OfficeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFundSourceByUUID = `-- name: GetFundSourceByUUID :one
SELECT fund_source_uuid, name, source_type, currency, balance, available_balance, bank_info, bin, bank_account_number, bank_account_owner, cash_owner, tenant_id, office_id
FROM treasury.fund_sources
WHERE fund_source_uuid = $1
`

func (q *Queries) GetFundSourceByUUID(ctx context.Context, fundSourceUuid domain.FundSourceUUID) (TreasuryFundSource, error) {
	row := q.db.QueryRow(ctx, getFundSourceByUUID, fundSourceUuid)
	var i TreasuryFundSource
	err := row.Scan(
		&i.FundSourceUuid,
		&i.Name,
		&i.SourceType,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.BankInfo,
		&i.Bin,
		&i.BankAccountNumber,
		&i.BankAccountOwner,
		&i.CashOwner,
		&i.TenantID,
		&i.OfficeID,
	)
	return i, err
}

const getFundSourcesByUUIDs = `-- name: GetFundSourcesByUUIDs :many
SELECT fund_source_uuid, name, source_type, currency, balance, available_balance, bank_info, bin, bank_account_number, bank_account_owner, cash_owner, tenant_id, office_id
FROM treasury.fund_sources
WHERE fund_source_uuid = ANY($1::uuid[]) 
  AND tenant_id = $2
  AND office_id = $3
`

type GetFundSourcesByUUIDsParams struct {
	FundSourceUuids []common.UUID
	TenantID        string
	OfficeID        string
}

func (q *Queries) GetFundSourcesByUUIDs(ctx context.Context, arg GetFundSourcesByUUIDsParams) ([]TreasuryFundSource, error) {
	rows, err := q.db.Query(ctx, getFundSourcesByUUIDs, arg.FundSourceUuids, arg.TenantID, arg.OfficeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreasuryFundSource{}
	for rows.Next() {
		var i TreasuryFundSource
		if err := rows.Scan(
			&i.FundSourceUuid,
			&i.Name,
			&i.SourceType,
			&i.Currency,
			&i.Balance,
			&i.AvailableBalance,
			&i.BankInfo,
			&i.Bin,
			&i.BankAccountNumber,
			&i.BankAccountOwner,
			&i.CashOwner,
			&i.TenantID,
			&i.OfficeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFundSource = `-- name: InsertFundSource :exec
INSERT INTO treasury.fund_sources (
    fund_source_uuid,
    name,
    source_type,
    balance,
    available_balance,
    currency,
    bank_info,
    bin,
    bank_account_number,
    bank_account_owner,
    cash_owner,
    tenant_id,
    office_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
`

type InsertFundSourceParams struct {
	FundSourceUuid    domain.FundSourceUUID
	Name              string
	SourceType        domain.FundSourceType
	Balance           decimal.Decimal
	AvailableBalance  decimal.Decimal
	Currency          shared.Currency
	BankInfo          domain.BankInfo
	Bin               *string
	BankAccountNumber *string
	BankAccountOwner  *string
	CashOwner         *string
	TenantID          string
	OfficeID          string
}

func (q *Queries) InsertFundSource(ctx context.Context, arg InsertFundSourceParams) error {
	_, err := q.db.Exec(ctx, insertFundSource,
		arg.FundSourceUuid,
		arg.Name,
		arg.SourceType,
		arg.Balance,
		arg.AvailableBalance,
		arg.Currency,
		arg.BankInfo,
		arg.Bin,
		arg.BankAccountNumber,
		arg.BankAccountOwner,
		arg.CashOwner,
		arg.TenantID,
		arg.OfficeID,
	)
	return err
}

const listFundSources = `-- name: ListFundSources :many
SELECT fund_source_uuid, name, source_type, currency, balance, available_balance, bank_info, bin, bank_account_number, bank_account_owner, cash_owner, tenant_id, office_id
FROM treasury.fund_sources
WHERE tenant_id = $1
  AND office_id = $2
ORDER BY fund_source_uuid ASC
LIMIT $4 
OFFSET $3
`

type ListFundSourcesParams struct {
	TenantID  string
	OfficeID  string
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) ListFundSources(ctx context.Context, arg ListFundSourcesParams) ([]TreasuryFundSource, error) {
	rows, err := q.db.Query(ctx, listFundSources,
		arg.TenantID,
		arg.OfficeID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreasuryFundSource{}
	for rows.Next() {
		var i TreasuryFundSource
		if err := rows.Scan(
			&i.FundSourceUuid,
			&i.Name,
			&i.SourceType,
			&i.Currency,
			&i.Balance,
			&i.AvailableBalance,
			&i.BankInfo,
			&i.Bin,
			&i.BankAccountNumber,
			&i.BankAccountOwner,
			&i.CashOwner,
			&i.TenantID,
			&i.OfficeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFundSourceAvailableBalance = `-- name: UpdateFundSourceAvailableBalance :exec
UPDATE treasury.fund_sources
SET available_balance = $1
WHERE fund_source_uuid = $2
`

type UpdateFundSourceAvailableBalanceParams struct {
	NewAvailableBalance decimal.Decimal
	FundSourceUuid      domain.FundSourceUUID
}

func (q *Queries) UpdateFundSourceAvailableBalance(ctx context.Context, arg UpdateFundSourceAvailableBalanceParams) error {
	_, err := q.db.Exec(ctx, updateFundSourceAvailableBalance, arg.NewAvailableBalance, arg.FundSourceUuid)
	return err
}
