// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fund_sources.sql

package dbmodels

import (
	"context"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"
)

const getFundSourceByUUID = `-- name: GetFundSourceByUUID :one
SELECT fund_source_uuid, name, source_type, currency, balance, available_balance, bank_info, bank_code, bank_account_number, bank_account_owner, cash_owner
FROM treasury.fund_sources
WHERE fund_source_uuid = $1
`

func (q *Queries) GetFundSourceByUUID(ctx context.Context, fundSourceUuid domain.FundSourceUUID) (TreasuryFundSource, error) {
	row := q.db.QueryRow(ctx, getFundSourceByUUID, fundSourceUuid)
	var i TreasuryFundSource
	err := row.Scan(
		&i.FundSourceUuid,
		&i.Name,
		&i.SourceType,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.BankInfo,
		&i.BankCode,
		&i.BankAccountNumber,
		&i.BankAccountOwner,
		&i.CashOwner,
	)
	return i, err
}

const insertFundSource = `-- name: InsertFundSource :exec
INSERT INTO treasury.fund_sources (
    fund_source_uuid,
    name,
    source_type,
    balance,
    available_balance,
    currency,
    bank_info,
    bank_code,
    bank_account_number,
    bank_account_owner,
    cash_owner
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type InsertFundSourceParams struct {
	FundSourceUuid    domain.FundSourceUUID
	Name              string
	SourceType        domain.FundSourceType
	Balance           decimal.Decimal
	AvailableBalance  decimal.Decimal
	Currency          shared.Currency
	BankInfo          domain.BankInfo
	BankCode          *string
	BankAccountNumber *string
	BankAccountOwner  *string
	CashOwner         *string
}

func (q *Queries) InsertFundSource(ctx context.Context, arg InsertFundSourceParams) error {
	_, err := q.db.Exec(ctx, insertFundSource,
		arg.FundSourceUuid,
		arg.Name,
		arg.SourceType,
		arg.Balance,
		arg.AvailableBalance,
		arg.Currency,
		arg.BankInfo,
		arg.BankCode,
		arg.BankAccountNumber,
		arg.BankAccountOwner,
		arg.CashOwner,
	)
	return err
}
