// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journal_entries.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"
)

type BatchInsertJournalEntriesParams struct {
	JournalEntryUuid domain.JournalEntryUUID
	FundSourceUuid   domain.FundSourceUUID
	Amount           decimal.Decimal
	EntryType        shared.EntryType
	BalanceBefore    decimal.Decimal
	BalanceAfter     decimal.Decimal
	Status           domain.JournalEntryStatus
	TransactionDate  time.Time
	TransactionNo    *string
	Description      *string
	CreatedAt        time.Time
	CreatedBy        string
}

const countJournalEntries = `-- name: CountJournalEntries :one
SELECT COUNT(*)
FROM treasury.journal_entries
WHERE 
    fund_source_uuid = $1
    AND ($2::timestamptz IS NULL 
        OR transaction_date >= $2::timestamptz)
    AND ($3::timestamptz IS NULL 
        OR transaction_date <= $3::timestamptz)
`

type CountJournalEntriesParams struct {
	FundSourceUuid domain.FundSourceUUID
	DateFrom       *time.Time
	DateTo         *time.Time
}

func (q *Queries) CountJournalEntries(ctx context.Context, arg CountJournalEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJournalEntries, arg.FundSourceUuid, arg.DateFrom, arg.DateTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getJournalEntryByUID = `-- name: GetJournalEntryByUID :one
SELECT journal_entry_uuid, fund_source_uuid, amount, entry_type, balance_before, balance_after, status, transaction_date, transaction_no, description, reverse_entry_uuid, voided_by, voided_at, voided_reason, created_at, created_by, updated_at, updated_by
FROM treasury.journal_entries
WHERE journal_entry_uuid = $1
`

func (q *Queries) GetJournalEntryByUID(ctx context.Context, journalEntryUuid domain.JournalEntryUUID) (TreasuryJournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByUID, journalEntryUuid)
	var i TreasuryJournalEntry
	err := row.Scan(
		&i.JournalEntryUuid,
		&i.FundSourceUuid,
		&i.Amount,
		&i.EntryType,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.Status,
		&i.TransactionDate,
		&i.TransactionNo,
		&i.Description,
		&i.ReverseEntryUuid,
		&i.VoidedBy,
		&i.VoidedAt,
		&i.VoidedReason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT journal_entry_uuid, fund_source_uuid, amount, entry_type, balance_before, balance_after, status, transaction_date, transaction_no, description, reverse_entry_uuid, voided_by, voided_at, voided_reason, created_at, created_by, updated_at, updated_by
FROM treasury.journal_entries
WHERE 
    fund_source_uuid = $1 
    AND ($2::timestamptz IS NULL 
        OR transaction_date >= $2::timestamptz)
    AND ($3::timestamptz IS NULL 
        OR transaction_date <= $3::timestamptz)
ORDER BY 
    transaction_date DESC, 
    journal_entry_uuid DESC
LIMIT $5
OFFSET $4
`

type ListJournalEntriesParams struct {
	FundSourceUuid domain.FundSourceUUID
	DateFrom       *time.Time
	DateTo         *time.Time
	PageOffset     int32
	PageLimit      int32
}

func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]TreasuryJournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntries,
		arg.FundSourceUuid,
		arg.DateFrom,
		arg.DateTo,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreasuryJournalEntry{}
	for rows.Next() {
		var i TreasuryJournalEntry
		if err := rows.Scan(
			&i.JournalEntryUuid,
			&i.FundSourceUuid,
			&i.Amount,
			&i.EntryType,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Status,
			&i.TransactionDate,
			&i.TransactionNo,
			&i.Description,
			&i.ReverseEntryUuid,
			&i.VoidedBy,
			&i.VoidedAt,
			&i.VoidedReason,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJournalEntry = `-- name: UpdateJournalEntry :exec
UPDATE treasury.journal_entries
SET
    status             = $1,
    reverse_entry_uuid = $2,
    voided_by          = $3,
    voided_at          = $4,
    voided_reason      = $5,
    updated_at         = $6,
    updated_by         = $7
WHERE journal_entry_uuid = $8
`

type UpdateJournalEntryParams struct {
	Status           domain.JournalEntryStatus
	ReverseEntryUuid *domain.JournalEntryUUID
	VoidedBy         *string
	VoidedAt         *time.Time
	VoidedReason     *string
	UpdatedAt        *time.Time
	UpdatedBy        *string
	JournalEntryUuid domain.JournalEntryUUID
}

func (q *Queries) UpdateJournalEntry(ctx context.Context, arg UpdateJournalEntryParams) error {
	_, err := q.db.Exec(ctx, updateJournalEntry,
		arg.Status,
		arg.ReverseEntryUuid,
		arg.VoidedBy,
		arg.VoidedAt,
		arg.VoidedReason,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.JournalEntryUuid,
	)
	return err
}
