// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journal_entries.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"
)

type BatchInsertJournalEntriesParams struct {
	JournalEntryUuid domain.JournalEntryUUID
	FundSourceUuid   domain.FundSourceUUID
	Amount           decimal.Decimal
	EntryType        shared.EntryType
	BalanceBefore    decimal.Decimal
	BalanceAfter     decimal.Decimal
	Status           domain.JournalEntryStatus
	TransactionDate  time.Time
	TransactionNo    *string
	Description      *string
	CreatedAt        time.Time
	CreatedBy        string
}

const getJournalEntryByUID = `-- name: GetJournalEntryByUID :one
SELECT journal_entry_uuid, fund_source_uuid, amount, entry_type, balance_before, balance_after, status, transaction_date, transaction_no, description, reverse_entry_uuid, voided_by, voided_at, voided_reason, created_at, created_by, updated_at, updated_by
FROM treasury.journal_entries
WHERE journal_entry_uuid = $1
`

func (q *Queries) GetJournalEntryByUID(ctx context.Context, journalEntryUuid domain.JournalEntryUUID) (TreasuryJournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByUID, journalEntryUuid)
	var i TreasuryJournalEntry
	err := row.Scan(
		&i.JournalEntryUuid,
		&i.FundSourceUuid,
		&i.Amount,
		&i.EntryType,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.Status,
		&i.TransactionDate,
		&i.TransactionNo,
		&i.Description,
		&i.ReverseEntryUuid,
		&i.VoidedBy,
		&i.VoidedAt,
		&i.VoidedReason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateJournalEntry = `-- name: UpdateJournalEntry :exec
UPDATE treasury.journal_entries
SET
    status             = $1,
    reverse_entry_uuid = $2,
    voided_by          = $3,
    voided_at          = $4,
    voided_reason      = $5,
    updated_at         = $6,
    updated_by         = $7
WHERE journal_entry_uuid = $8
`

type UpdateJournalEntryParams struct {
	Status           domain.JournalEntryStatus
	ReverseEntryUuid *domain.JournalEntryUUID
	VoidedBy         *string
	VoidedAt         *time.Time
	VoidedReason     *string
	UpdatedAt        *time.Time
	UpdatedBy        *string
	JournalEntryUuid domain.JournalEntryUUID
}

func (q *Queries) UpdateJournalEntry(ctx context.Context, arg UpdateJournalEntryParams) error {
	_, err := q.db.Exec(ctx, updateJournalEntry,
		arg.Status,
		arg.ReverseEntryUuid,
		arg.VoidedBy,
		arg.VoidedAt,
		arg.VoidedReason,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.JournalEntryUuid,
	)
	return err
}
