// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"database/sql/driver"
	"fmt"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"
)

type TreasuryFundSourceType string

const (
	TreasuryFundSourceTypeBANK TreasuryFundSourceType = "BANK"
	TreasuryFundSourceTypeCASH TreasuryFundSourceType = "CASH"
)

func (e *TreasuryFundSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TreasuryFundSourceType(s)
	case string:
		*e = TreasuryFundSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for TreasuryFundSourceType: %T", src)
	}
	return nil
}

type NullTreasuryFundSourceType struct {
	TreasuryFundSourceType TreasuryFundSourceType
	Valid                  bool // Valid is true if TreasuryFundSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTreasuryFundSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.TreasuryFundSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TreasuryFundSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTreasuryFundSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TreasuryFundSourceType), nil
}

type TreasuryFundSource struct {
	FundSourceUuid    domain.FundSourceUUID
	Name              string
	SourceType        domain.FundSourceType
	Currency          shared.Currency
	Balance           decimal.Decimal
	AvailableBalance  decimal.Decimal
	BankInfo          domain.BankInfo
	BankCode          *string
	BankAccountNumber *string
	BankAccountOwner  *string
	CashOwner         *string
}
