// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"
)

const getTransactionByUUID = `-- name: GetTransactionByUUID :one
SELECT transaction_uuid, status, entry_type, amount, currency, description, transaction_date, tenant_id, office_id, fund_source_uuid, wallet_uuid, reversed_transaction_uuid
FROM treasury.transactions
WHERE transaction_uuid = $1
`

func (q *Queries) GetTransactionByUUID(ctx context.Context, transactionUuid domain.TransactionUUID) (TreasuryTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByUUID, transactionUuid)
	var i TreasuryTransaction
	err := row.Scan(
		&i.TransactionUuid,
		&i.Status,
		&i.EntryType,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.TransactionDate,
		&i.TenantID,
		&i.OfficeID,
		&i.FundSourceUuid,
		&i.WalletUuid,
		&i.ReversedTransactionUuid,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO treasury.transactions (
    transaction_uuid,
    status,
    entry_type,
    amount,
    currency,
    description,
    transaction_date,
    tenant_id,
    office_id,
    fund_source_uuid,
    wallet_uuid,
    reversed_transaction_uuid
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type InsertTransactionParams struct {
	TransactionUuid         domain.TransactionUUID
	Status                  domain.TransactionStatus
	EntryType               shared.EntryType
	Amount                  decimal.Decimal
	Currency                shared.Currency
	Description             *string
	TransactionDate         time.Time
	TenantID                string
	OfficeID                string
	FundSourceUuid          domain.FundSourceUUID
	WalletUuid              *domain.WalletUUID
	ReversedTransactionUuid *domain.TransactionUUID
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.TransactionUuid,
		arg.Status,
		arg.EntryType,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.TransactionDate,
		arg.TenantID,
		arg.OfficeID,
		arg.FundSourceUuid,
		arg.WalletUuid,
		arg.ReversedTransactionUuid,
	)
	return err
}
