// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package dbmodels

import (
	"context"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"
)

const getWalletByUUID = `-- name: GetWalletByUUID :one
SELECT wallet_uuid, name, currency, balance, tenant_id, office_id
FROM treasury.wallets
WHERE wallet_uuid = $1
    AND tenant_id = $2
    AND office_id = $3
`

type GetWalletByUUIDParams struct {
	WalletUuid domain.WalletUUID
	TenantID   string
	OfficeID   string
}

func (q *Queries) GetWalletByUUID(ctx context.Context, arg GetWalletByUUIDParams) (TreasuryWallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUUID, arg.WalletUuid, arg.TenantID, arg.OfficeID)
	var i TreasuryWallet
	err := row.Scan(
		&i.WalletUuid,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.TenantID,
		&i.OfficeID,
	)
	return i, err
}

const insertWallet = `-- name: InsertWallet :exec
INSERT INTO treasury.wallets (
    wallet_uuid,
    name,
    currency,
    balance,
    tenant_id,
    office_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertWalletParams struct {
	WalletUuid domain.WalletUUID
	Name       string
	Currency   shared.Currency
	Balance    decimal.Decimal
	TenantID   string
	OfficeID   string
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) error {
	_, err := q.db.Exec(ctx, insertWallet,
		arg.WalletUuid,
		arg.Name,
		arg.Currency,
		arg.Balance,
		arg.TenantID,
		arg.OfficeID,
	)
	return err
}
