// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package dbmodels

import (
	"context"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"
)

const countWallets = `-- name: CountWallets :one
SELECT COUNT(*)
FROM treasury.wallets
WHERE tenant_id = $1
  AND office_id = $2
`

type CountWalletsParams struct {
	TenantID string
	OfficeID string
}

func (q *Queries) CountWallets(ctx context.Context, arg CountWalletsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWallets, arg.TenantID, arg.OfficeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWalletByUUID = `-- name: GetWalletByUUID :one
SELECT wallet_uuid, name, currency, balance, tenant_id, office_id
FROM treasury.wallets
WHERE wallet_uuid = $1
    AND tenant_id = $2
    AND office_id = $3
`

type GetWalletByUUIDParams struct {
	WalletUuid domain.WalletUUID
	TenantID   string
	OfficeID   string
}

func (q *Queries) GetWalletByUUID(ctx context.Context, arg GetWalletByUUIDParams) (TreasuryWallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUUID, arg.WalletUuid, arg.TenantID, arg.OfficeID)
	var i TreasuryWallet
	err := row.Scan(
		&i.WalletUuid,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.TenantID,
		&i.OfficeID,
	)
	return i, err
}

const insertWallet = `-- name: InsertWallet :exec
INSERT INTO treasury.wallets (
    wallet_uuid,
    name,
    currency,
    balance,
    tenant_id,
    office_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertWalletParams struct {
	WalletUuid domain.WalletUUID
	Name       string
	Currency   shared.Currency
	Balance    decimal.Decimal
	TenantID   string
	OfficeID   string
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) error {
	_, err := q.db.Exec(ctx, insertWallet,
		arg.WalletUuid,
		arg.Name,
		arg.Currency,
		arg.Balance,
		arg.TenantID,
		arg.OfficeID,
	)
	return err
}

const listWallets = `-- name: ListWallets :many
SELECT wallet_uuid, name, currency, balance, tenant_id, office_id
FROM treasury.wallets
WHERE tenant_id = $1
  AND office_id = $2
ORDER BY wallet_uuid ASC
LIMIT $4
OFFSET $3
`

type ListWalletsParams struct {
	TenantID  string
	OfficeID  string
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) ListWallets(ctx context.Context, arg ListWalletsParams) ([]TreasuryWallet, error) {
	rows, err := q.db.Query(ctx, listWallets,
		arg.TenantID,
		arg.OfficeID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreasuryWallet{}
	for rows.Next() {
		var i TreasuryWallet
		if err := rows.Scan(
			&i.WalletUuid,
			&i.Name,
			&i.Currency,
			&i.Balance,
			&i.TenantID,
			&i.OfficeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE treasury.wallets
SET balance = $1
WHERE wallet_uuid = $2
`

type UpdateWalletBalanceParams struct {
	Balance    decimal.Decimal
	WalletUuid domain.WalletUUID
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.Balance, arg.WalletUuid)
	return err
}
