// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package dbmodels

import (
	"context"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/treasury/domain"
)

const countWallets = `-- name: CountWallets :one
SELECT COUNT(*)
FROM treasury.wallets
WHERE tenant_id = $1
  AND office_id = $2
`

type CountWalletsParams struct {
	TenantID string
	OfficeID string
}

func (q *Queries) CountWallets(ctx context.Context, arg CountWalletsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWallets, arg.TenantID, arg.OfficeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWalletByUUID = `-- name: GetWalletByUUID :one
SELECT wallet_uuid, name, currency, balance, tenant_id, office_id
FROM treasury.wallets
WHERE wallet_uuid = $1
    AND tenant_id = $2
    AND office_id = $3
`

type GetWalletByUUIDParams struct {
	WalletUuid domain.WalletUUID
	TenantID   string
	OfficeID   string
}

func (q *Queries) GetWalletByUUID(ctx context.Context, arg GetWalletByUUIDParams) (TreasuryWallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUUID, arg.WalletUuid, arg.TenantID, arg.OfficeID)
	var i TreasuryWallet
	err := row.Scan(
		&i.WalletUuid,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.TenantID,
		&i.OfficeID,
	)
	return i, err
}

const getWalletsWithAllocationsByUUIDs = `-- name: GetWalletsWithAllocationsByUUIDs :many
WITH requested_pairs AS (
    SELECT unnest($3::uuid[]) AS wallet_uuid,
           unnest($4::uuid[]) AS fund_source_uuid
)
SELECT w.wallet_uuid, w.name, w.currency, w.balance, w.tenant_id, w.office_id, wa.wallet_uuid, wa.fund_source_uuid, wa.balance, fs.fund_source_uuid, fs.name, fs.source_type, fs.currency, fs.balance, fs.available_balance, fs.bank_info, fs.bin, fs.bank_account_number, fs.bank_account_owner, fs.cash_owner, fs.tenant_id, fs.office_id
FROM treasury.wallets w
JOIN requested_pairs rp ON rp.wallet_uuid = w.wallet_uuid
JOIN treasury.wallet_allocations wa
    ON wa.wallet_uuid = rp.wallet_uuid AND wa.fund_source_uuid = rp.fund_source_uuid
JOIN treasury.fund_sources fs ON fs.fund_source_uuid = wa.fund_source_uuid
WHERE w.tenant_id = $1
  AND w.office_id = $2
`

type GetWalletsWithAllocationsByUUIDsParams struct {
	TenantID        string
	OfficeID        string
	WalletUuids     []common.UUID
	FundSourceUuids []common.UUID
}

type GetWalletsWithAllocationsByUUIDsRow struct {
	TreasuryWallet           TreasuryWallet
	TreasuryWalletAllocation TreasuryWalletAllocation
	TreasuryFundSource       TreasuryFundSource
}

func (q *Queries) GetWalletsWithAllocationsByUUIDs(ctx context.Context, arg GetWalletsWithAllocationsByUUIDsParams) ([]GetWalletsWithAllocationsByUUIDsRow, error) {
	rows, err := q.db.Query(ctx, getWalletsWithAllocationsByUUIDs,
		arg.TenantID,
		arg.OfficeID,
		arg.WalletUuids,
		arg.FundSourceUuids,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWalletsWithAllocationsByUUIDsRow{}
	for rows.Next() {
		var i GetWalletsWithAllocationsByUUIDsRow
		if err := rows.Scan(
			&i.TreasuryWallet.WalletUuid,
			&i.TreasuryWallet.Name,
			&i.TreasuryWallet.Currency,
			&i.TreasuryWallet.Balance,
			&i.TreasuryWallet.TenantID,
			&i.TreasuryWallet.OfficeID,
			&i.TreasuryWalletAllocation.WalletUuid,
			&i.TreasuryWalletAllocation.FundSourceUuid,
			&i.TreasuryWalletAllocation.Balance,
			&i.TreasuryFundSource.FundSourceUuid,
			&i.TreasuryFundSource.Name,
			&i.TreasuryFundSource.SourceType,
			&i.TreasuryFundSource.Currency,
			&i.TreasuryFundSource.Balance,
			&i.TreasuryFundSource.AvailableBalance,
			&i.TreasuryFundSource.BankInfo,
			&i.TreasuryFundSource.Bin,
			&i.TreasuryFundSource.BankAccountNumber,
			&i.TreasuryFundSource.BankAccountOwner,
			&i.TreasuryFundSource.CashOwner,
			&i.TreasuryFundSource.TenantID,
			&i.TreasuryFundSource.OfficeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWallet = `-- name: InsertWallet :exec
INSERT INTO treasury.wallets (
    wallet_uuid,
    name,
    currency,
    balance,
    tenant_id,
    office_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertWalletParams struct {
	WalletUuid domain.WalletUUID
	Name       string
	Currency   shared.Currency
	Balance    decimal.Decimal
	TenantID   string
	OfficeID   string
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) error {
	_, err := q.db.Exec(ctx, insertWallet,
		arg.WalletUuid,
		arg.Name,
		arg.Currency,
		arg.Balance,
		arg.TenantID,
		arg.OfficeID,
	)
	return err
}

const listWallets = `-- name: ListWallets :many
SELECT wallet_uuid, name, currency, balance, tenant_id, office_id
FROM treasury.wallets
WHERE tenant_id = $1
  AND office_id = $2
ORDER BY wallet_uuid ASC
LIMIT $4
OFFSET $3
`

type ListWalletsParams struct {
	TenantID  string
	OfficeID  string
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) ListWallets(ctx context.Context, arg ListWalletsParams) ([]TreasuryWallet, error) {
	rows, err := q.db.Query(ctx, listWallets,
		arg.TenantID,
		arg.OfficeID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreasuryWallet{}
	for rows.Next() {
		var i TreasuryWallet
		if err := rows.Scan(
			&i.WalletUuid,
			&i.Name,
			&i.Currency,
			&i.Balance,
			&i.TenantID,
			&i.OfficeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE treasury.wallets
SET balance = $1
WHERE wallet_uuid = $2
`

type UpdateWalletBalanceParams struct {
	Balance    decimal.Decimal
	WalletUuid domain.WalletUUID
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.Balance, arg.WalletUuid)
	return err
}
