// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	fundprovider "sumni-finance-backend/internal/finance/domain/fundprovider"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, fp
func (_m *MockRepository) Create(ctx context.Context, fp *fundprovider.FundProvider) error {
	ret := _m.Called(ctx, fp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fundprovider.FundProvider) error); ok {
		r0 = rf(ctx, fp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - fp *fundprovider.FundProvider
func (_e *MockRepository_Expecter) Create(ctx interface{}, fp interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, fp)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, fp *fundprovider.FundProvider)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*fundprovider.FundProvider))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *fundprovider.FundProvider) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, fpID
func (_m *MockRepository) GetByID(ctx context.Context, fpID uuid.UUID) (*fundprovider.FundProvider, error) {
	ret := _m.Called(ctx, fpID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *fundprovider.FundProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*fundprovider.FundProvider, error)); ok {
		return rf(ctx, fpID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *fundprovider.FundProvider); ok {
		r0 = rf(ctx, fpID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fundprovider.FundProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, fpID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - fpID uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, fpID interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, fpID)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, fpID uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 *fundprovider.FundProvider, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*fundprovider.FundProvider, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function with given fields: ctx, fpID
func (_m *MockRepository) GetByIDs(ctx context.Context, fpID []uuid.UUID) ([]*fundprovider.FundProvider, error) {
	ret := _m.Called(ctx, fpID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*fundprovider.FundProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*fundprovider.FundProvider, error)); ok {
		return rf(ctx, fpID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*fundprovider.FundProvider); ok {
		r0 = rf(ctx, fpID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*fundprovider.FundProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, fpID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - fpID []uuid.UUID
func (_e *MockRepository_Expecter) GetByIDs(ctx interface{}, fpID interface{}) *MockRepository_GetByIDs_Call {
	return &MockRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, fpID)}
}

func (_c *MockRepository_GetByIDs_Call) Run(run func(ctx context.Context, fpID []uuid.UUID)) *MockRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetByIDs_Call) Return(_a0 []*fundprovider.FundProvider, _a1 error) *MockRepository_GetByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]*fundprovider.FundProvider, error)) *MockRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
