// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ports

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AllocateFundRequest defines model for AllocateFundRequest.
type AllocateFundRequest struct {
	// Providers List of fund providers to allocate from
	Providers []AllocatedProvider `json:"providers"`
}

// AllocatedProvider defines model for AllocatedProvider.
type AllocatedProvider struct {
	// AllocatedAmount Amount to allocate from this provider
	AllocatedAmount int64 `json:"allocatedAmount"`

	// Id Fund provider ID
	Id openapi_types.UUID `json:"id"`
}

// CreateFundProviderRequest defines model for CreateFundProviderRequest.
type CreateFundProviderRequest struct {
	// Currency Currency code (e.g., USD, VND, KRW)
	Currency string `json:"currency"`

	// FpType Type of fund provider (BANK for bank accounts, CASH for cash holdings)
	FpType string `json:"fpType"`

	// InitBalance Initial balance for the fund provider
	InitBalance int64 `json:"initBalance"`

	// Name Fund provider name followed by the last 4 digits of the account number (e.g., Techcombank 7316)
	Name string `json:"name"`
}

// CreateWalletRequest defines model for CreateWalletRequest.
type CreateWalletRequest struct {
	// Currency Currency code (e.g., USD, VND, KRW)
	Currency string `json:"currency"`

	// Name Wallet Name (tai chinh tong, quy van phong, ...)
	Name string `json:"name"`
}

// CreateWalletResponse defines model for CreateWalletResponse.
type CreateWalletResponse struct {
	// RequestId Request identifier for tracking
	RequestId *string `json:"request_id,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Message Human-readable error message
		Message string `json:"message"`

		// Slug Error slug identifier
		Slug string `json:"slug"`
	} `json:"error"`

	// RequestId Request identifier for tracking
	RequestId string `json:"request_id"`
}

// OpenAccountingPeriodRequest defines model for OpenAccountingPeriodRequest.
type OpenAccountingPeriodRequest struct {
	// Month The month for the accounting period (1-12)
	Month int `json:"month"`

	// WalletId The wallet ID to open accounting period for
	WalletId openapi_types.UUID `json:"walletId"`

	// Year The year for the accounting period
	Year int `json:"year"`
}

// RecordTransactionRecordsRequest defines model for RecordTransactionRecordsRequest.
type RecordTransactionRecordsRequest struct {
	// TransactionRecords List of transaction records to record
	TransactionRecords []TransactionRecord `json:"transactionRecords"`

	// YearMonth The year and month in YYYY-MM format
	YearMonth string `json:"yearMonth"`
}

// TransactionRecord defines model for TransactionRecord.
type TransactionRecord struct {
	// Amount Transaction amount
	Amount int64 `json:"amount"`

	// Description Transaction description
	Description string `json:"description"`

	// FundProviderId Fund provider ID
	FundProviderId openapi_types.UUID `json:"fundProviderId"`

	// TransactionNo Transaction number or reference
	TransactionNo string `json:"transactionNo"`

	// TransactionType Type of transaction (e.g., DEPOSIT, WITHDRAWAL, TRANSFER)
	TransactionType string `json:"transactionType"`
}

// CreateFundProviderJSONRequestBody defines body for CreateFundProvider for application/json ContentType.
type CreateFundProviderJSONRequestBody = CreateFundProviderRequest

// CreateWalletJSONRequestBody defines body for CreateWallet for application/json ContentType.
type CreateWalletJSONRequestBody = CreateWalletRequest

// RecordTransactionRecordsJSONRequestBody defines body for RecordTransactionRecords for application/json ContentType.
type RecordTransactionRecordsJSONRequestBody = RecordTransactionRecordsRequest

// OpenAccountingPeriodJSONRequestBody defines body for OpenAccountingPeriod for application/json ContentType.
type OpenAccountingPeriodJSONRequestBody = OpenAccountingPeriodRequest

// AllocateFundJSONRequestBody defines body for AllocateFund for application/json ContentType.
type AllocateFundJSONRequestBody = AllocateFundRequest
