// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"time"

	"sumni-finance-backend/internal/identity/app/models"
)

type IdentitiesSession struct {
	SessionID          models.SessionID
	UserSubject        string
	IDToken            string
	AccessToken        string
	RefreshToken       string
	ActiveOrganization string
	ActiveOffice       string
	IsExpired          bool
	ExpiresAt          time.Time
	CreatedAt          time.Time
	UpdatedAt          *time.Time
}
