// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbmodels

import (
	"context"
	"time"

	"sumni-finance-backend/internal/identity/app/models"
)

const expireSessionByID = `-- name: ExpireSessionByID :exec
UPDATE identities.sessions
SET is_expired = TRUE, updated_at = NOW()
WHERE session_id = $1
`

func (q *Queries) ExpireSessionByID(ctx context.Context, sessionID models.SessionID) error {
	_, err := q.db.Exec(ctx, expireSessionByID, sessionID)
	return err
}

const getActiveSessionByID = `-- name: GetActiveSessionByID :one
SELECT session_id, user_subject, id_token, access_token, refresh_token, active_organization, active_office, is_expired, expires_at, created_at, updated_at FROM identities.sessions
WHERE session_id = $1 
    AND is_expired = false
`

func (q *Queries) GetActiveSessionByID(ctx context.Context, sessionID models.SessionID) (IdentitiesSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByID, sessionID)
	var i IdentitiesSession
	err := row.Scan(
		&i.SessionID,
		&i.UserSubject,
		&i.IDToken,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ActiveOrganization,
		&i.ActiveOffice,
		&i.IsExpired,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO identities.sessions (
    session_id,
    user_subject,
    id_token,
    access_token,
    refresh_token,
    active_organization,
    active_office,
    is_expired,
    expires_at,
    created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (user_subject) WHERE is_expired = FALSE 
DO UPDATE SET
    session_id = EXCLUDED.session_id,
    id_token = EXCLUDED.id_token,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    active_organization = EXCLUDED.active_organization,
    active_office = EXCLUDED.active_office,
    expires_at = EXCLUDED.expires_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertSessionParams struct {
	SessionID          models.SessionID
	UserSubject        string
	IDToken            string
	AccessToken        string
	RefreshToken       string
	ActiveOrganization string
	ActiveOffice       string
	IsExpired          bool
	ExpiresAt          time.Time
	CreatedAt          time.Time
	UpdatedAt          *time.Time
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.Exec(ctx, upsertSession,
		arg.SessionID,
		arg.UserSubject,
		arg.IDToken,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ActiveOrganization,
		arg.ActiveOffice,
		arg.IsExpired,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
