// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fund_provider.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const batchUpdateFundProvidersBalance = `-- name: BatchUpdateFundProvidersBalance :exec
UPDATE finance.fund_providers fp
SET
    balance = v.balance,
    unallocated_amount = v.unallocatated_amount,
    version = v.version + 1
FROM (
    SELECT
        unnest($1::uuid[]) as id,
        unnest($2::bigint[]) as balance,
        unnest($3::bigint[]) as unallocated_amount,
        unnest($4::int[]) as version
) as v
WHERE fp.id = v.id
  AND fp.version = v.version
`

type BatchUpdateFundProvidersBalanceParams struct {
	Ids                []uuid.UUID
	Balances           []int64
	UnallocatedAmounts []int64
	Versions           []int32
}

func (q *Queries) BatchUpdateFundProvidersBalance(ctx context.Context, arg BatchUpdateFundProvidersBalanceParams) error {
	_, err := q.db.Exec(ctx, batchUpdateFundProvidersBalance,
		arg.Ids,
		arg.Balances,
		arg.UnallocatedAmounts,
		arg.Versions,
	)
	return err
}

const createFundProvider = `-- name: CreateFundProvider :exec
INSERT INTO finance.fund_providers (
    id,
    name,
    fp_type,
    balance,
    currency,
    unallocated_amount,
    version
) VALUES(
    $1, -- id
    $2, -- name
    $3, -- fp_type
    $4, -- balance
    $5, -- currency
    $6, -- unallocated_amount
    $7  -- version
)
`

type CreateFundProviderParams struct {
	ID                uuid.UUID
	Name              string
	FpType            string
	Balance           int64
	Currency          string
	UnallocatedAmount int64
	Version           int32
}

func (q *Queries) CreateFundProvider(ctx context.Context, arg CreateFundProviderParams) error {
	_, err := q.db.Exec(ctx, createFundProvider,
		arg.ID,
		arg.Name,
		arg.FpType,
		arg.Balance,
		arg.Currency,
		arg.UnallocatedAmount,
		arg.Version,
	)
	return err
}

const getFundProviderByID = `-- name: GetFundProviderByID :one
SELECT
    id,
    name,
    fp_type,
    balance,
    unallocated_amount,
    currency,
    version
FROM finance.fund_providers
WHERE id = $1
`

type GetFundProviderByIDRow struct {
	ID                uuid.UUID
	Name              string
	FpType            string
	Balance           int64
	UnallocatedAmount int64
	Currency          string
	Version           int32
}

func (q *Queries) GetFundProviderByID(ctx context.Context, id uuid.UUID) (GetFundProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, getFundProviderByID, id)
	var i GetFundProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FpType,
		&i.Balance,
		&i.UnallocatedAmount,
		&i.Currency,
		&i.Version,
	)
	return i, err
}

const getFundProviderByWalletID = `-- name: GetFundProviderByWalletID :many
SELECT 
    fp.id,
    fp.name,
    fp.fp_type,
    fp.balance,
    fp.currency,
    fp.unallocated_amount,
    fp.version,
    fpa.allocated_amount AS wallet_allocated_amount
FROM finance.fund_providers fp
    INNER JOIN finance.fund_provider_allocations fpa
        ON fp.id = fpa.fund_provider_id
            AND fpa.wallet_id = $1
`

type GetFundProviderByWalletIDRow struct {
	ID                    uuid.UUID
	Name                  string
	FpType                string
	Balance               int64
	Currency              string
	UnallocatedAmount     int64
	Version               int32
	WalletAllocatedAmount int64
}

func (q *Queries) GetFundProviderByWalletID(ctx context.Context, walletID uuid.UUID) ([]GetFundProviderByWalletIDRow, error) {
	rows, err := q.db.Query(ctx, getFundProviderByWalletID, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFundProviderByWalletIDRow
	for rows.Next() {
		var i GetFundProviderByWalletIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FpType,
			&i.Balance,
			&i.Currency,
			&i.UnallocatedAmount,
			&i.Version,
			&i.WalletAllocatedAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFundProvidersByIDs = `-- name: GetFundProvidersByIDs :many
SELECT
    id,
    name,
    fp_type,
    balance,
    unallocated_amount,
    currency,
    version
FROM finance.fund_providers
WHERE id = ANY($1::uuid[])
`

type GetFundProvidersByIDsRow struct {
	ID                uuid.UUID
	Name              string
	FpType            string
	Balance           int64
	UnallocatedAmount int64
	Currency          string
	Version           int32
}

func (q *Queries) GetFundProvidersByIDs(ctx context.Context, fpids []uuid.UUID) ([]GetFundProvidersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getFundProvidersByIDs, fpids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFundProvidersByIDsRow
	for rows.Next() {
		var i GetFundProvidersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FpType,
			&i.Balance,
			&i.UnallocatedAmount,
			&i.Currency,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
