// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fund_provider.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFundProvider = `-- name: CreateFundProvider :exec
INSERT INTO finance.fund_providers (
    id,
    name,
    fp_type,
    balance,
    currency,
    unallocated_amount,
    version
) VALUES(
    $1, -- id
    $2, -- name
    $3, -- fp_type
    $4, -- balance
    $5, -- currency
    $6, -- unallocated_amount
    $7  -- version
)
`

type CreateFundProviderParams struct {
	ID                uuid.UUID
	Name              string
	FpType            string
	Balance           int64
	Currency          string
	UnallocatedAmount int64
	Version           int32
}

func (q *Queries) CreateFundProvider(ctx context.Context, arg CreateFundProviderParams) error {
	_, err := q.db.Exec(ctx, createFundProvider,
		arg.ID,
		arg.Name,
		arg.FpType,
		arg.Balance,
		arg.Currency,
		arg.UnallocatedAmount,
		arg.Version,
	)
	return err
}

const getFundProviderByID = `-- name: GetFundProviderByID :one
SELECT
    id,
    name,
    fp_type,
    balance,
    unallocated_amount,
    currency,
    version
FROM finance.fund_providers
WHERE id = $1
`

type GetFundProviderByIDRow struct {
	ID                uuid.UUID
	Name              string
	FpType            string
	Balance           int64
	UnallocatedAmount int64
	Currency          string
	Version           int32
}

func (q *Queries) GetFundProviderByID(ctx context.Context, id uuid.UUID) (GetFundProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, getFundProviderByID, id)
	var i GetFundProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FpType,
		&i.Balance,
		&i.UnallocatedAmount,
		&i.Currency,
		&i.Version,
	)
	return i, err
}

const getFundProviderByWalletID = `-- name: GetFundProviderByWalletID :many
SELECT 
    fp.id,
    fp.name,
    fp.fp_type,
    fp.balance,
    fp.currency,
    fp.unallocated_amount,
    fp.version,
    fpa.allocated_amount AS wallet_allocated_amount
FROM finance.fund_providers fp
    INNER JOIN finance.fund_provider_allocation fpa
        ON fp.id = fpa.fund_provider_id
            AND fpa.wallet_id = $1
`

type GetFundProviderByWalletIDRow struct {
	ID                    uuid.UUID
	Name                  string
	FpType                string
	Balance               int64
	Currency              string
	UnallocatedAmount     int64
	Version               int32
	WalletAllocatedAmount int64
}

func (q *Queries) GetFundProviderByWalletID(ctx context.Context, walletID uuid.UUID) ([]GetFundProviderByWalletIDRow, error) {
	rows, err := q.db.Query(ctx, getFundProviderByWalletID, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFundProviderByWalletIDRow
	for rows.Next() {
		var i GetFundProviderByWalletIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FpType,
			&i.Balance,
			&i.Currency,
			&i.UnallocatedAmount,
			&i.Version,
			&i.WalletAllocatedAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFundProvidersByIDs = `-- name: GetFundProvidersByIDs :many
SELECT
    id,
    name,
    fp_type,
    balance,
    unallocated_amount,
    currency,
    version
FROM finance.fund_providers
WHERE id = ANY($1::uuid[])
`

type GetFundProvidersByIDsRow struct {
	ID                uuid.UUID
	Name              string
	FpType            string
	Balance           int64
	UnallocatedAmount int64
	Currency          string
	Version           int32
}

func (q *Queries) GetFundProvidersByIDs(ctx context.Context, fpids []uuid.UUID) ([]GetFundProvidersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getFundProvidersByIDs, fpids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFundProvidersByIDsRow
	for rows.Next() {
		var i GetFundProvidersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FpType,
			&i.Balance,
			&i.UnallocatedAmount,
			&i.Currency,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFundProviderPartial = `-- name: UpdateFundProviderPartial :execrows
UPDATE finance.fund_providers
SET
    name = COALESCE($1, name),
    balance = COALESCE($2, balance),
    unallocated_amount = COALESCE($3, unallocated_amount),
    currency = COALESCE($4, currency),
    version = version + 1
WHERE id = $5
  AND version = $6
`

type UpdateFundProviderPartialParams struct {
	Name              pgtype.Text
	Balance           pgtype.Int8
	UnallocatedAmount pgtype.Int8
	Currency          pgtype.Text
	ID                uuid.UUID
	Version           int32
}

func (q *Queries) UpdateFundProviderPartial(ctx context.Context, arg UpdateFundProviderPartialParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFundProviderPartial,
		arg.Name,
		arg.Balance,
		arg.UnallocatedAmount,
		arg.Currency,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
