// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ledger.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type BulkInsertTransactionRecordsParams struct {
	ID                  uuid.UUID `db:"id"`
	TransactionNo       *string   `db:"transaction_no"`
	TransactionType     string    `db:"transaction_type"`
	Amount              int64     `db:"amount"`
	WalletBalance       int64     `db:"wallet_balance"`
	WalletID            uuid.UUID `db:"wallet_id"`
	FpID                uuid.UUID `db:"fp_id"`
	FpBalance           int64     `db:"fp_balance"`
	AccountingPeriodsID uuid.UUID `db:"accounting_periods_id"`
}

const createAccountingPeriod = `-- name: CreateAccountingPeriod :exec
INSERT INTO finance.accounting_periods (
    id,
    year_month,
    start_date,
    interval,
    end_time,
    wallet_opening_balance,
    total_debit,
    total_credit,
    wallet_closing_balance,
    version,
    wallet_id,
    status
) VALUES (
    $1, -- id
    $2, -- year_month
    $3, -- start_date
    $4, -- interval
    $5, -- end_time
    $6, -- wallet_opening_balance
    $7, -- total_debit
    $8, -- total_credit
    $9, -- wallet_closing_balance
    $10, -- version
    $11, -- wallet_id
    $12 -- status
)
`

type CreateAccountingPeriodParams struct {
	ID                   uuid.UUID `db:"id"`
	YearMonth            string    `db:"year_month"`
	StartDate            int32     `db:"start_date"`
	Interval             int32     `db:"interval"`
	EndTime              time.Time `db:"end_time"`
	WalletOpeningBalance int64     `db:"wallet_opening_balance"`
	TotalDebit           int64     `db:"total_debit"`
	TotalCredit          int64     `db:"total_credit"`
	WalletClosingBalance int64     `db:"wallet_closing_balance"`
	Version              *int32    `db:"version"`
	WalletID             uuid.UUID `db:"wallet_id"`
	Status               string    `db:"status"`
}

func (q *Queries) CreateAccountingPeriod(ctx context.Context, arg CreateAccountingPeriodParams) error {
	_, err := q.db.Exec(ctx, createAccountingPeriod,
		arg.ID,
		arg.YearMonth,
		arg.StartDate,
		arg.Interval,
		arg.EndTime,
		arg.WalletOpeningBalance,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.WalletClosingBalance,
		arg.Version,
		arg.WalletID,
		arg.Status,
	)
	return err
}

const getAccountingPeriodsByIDsAndWalletID = `-- name: GetAccountingPeriodsByIDsAndWalletID :many
SELECT
    id,
    year_month,
    start_date,
    interval,
    end_time,
    wallet_opening_balance,
    total_debit,
    total_credit,
    wallet_closing_balance,
    status,
    version
FROM
    finance.accounting_periods
WHERE wallet_id = $1 
    AND id = ANY($2::uuid[])
`

type GetAccountingPeriodsByIDsAndWalletIDParams struct {
	WalletID uuid.UUID   `db:"wallet_id"`
	Ids      []uuid.UUID `db:"ids"`
}

type GetAccountingPeriodsByIDsAndWalletIDRow struct {
	ID                   uuid.UUID `db:"id"`
	YearMonth            string    `db:"year_month"`
	StartDate            int32     `db:"start_date"`
	Interval             int32     `db:"interval"`
	EndTime              time.Time `db:"end_time"`
	WalletOpeningBalance int64     `db:"wallet_opening_balance"`
	TotalDebit           int64     `db:"total_debit"`
	TotalCredit          int64     `db:"total_credit"`
	WalletClosingBalance int64     `db:"wallet_closing_balance"`
	Status               string    `db:"status"`
	Version              *int32    `db:"version"`
}

func (q *Queries) GetAccountingPeriodsByIDsAndWalletID(ctx context.Context, arg GetAccountingPeriodsByIDsAndWalletIDParams) ([]GetAccountingPeriodsByIDsAndWalletIDRow, error) {
	rows, err := q.db.Query(ctx, getAccountingPeriodsByIDsAndWalletID, arg.WalletID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountingPeriodsByIDsAndWalletIDRow
	for rows.Next() {
		var i GetAccountingPeriodsByIDsAndWalletIDRow
		if err := rows.Scan(
			&i.ID,
			&i.YearMonth,
			&i.StartDate,
			&i.Interval,
			&i.EndTime,
			&i.WalletOpeningBalance,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.WalletClosingBalance,
			&i.Status,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountingPerid = `-- name: UpdateAccountingPerid :execrows
UPDATE finance.accounting_periods ap
SET
    total_debit = $1,
    total_credit = $2,
    wallet_closing_balance = $3,
    status = $4,
    version = version + 1
WHERE ap.id = $5
    AND ap.version = $6
`

type UpdateAccountingPeridParams struct {
	TotalDebit     int64     `db:"total_debit"`
	TotalCredit    int64     `db:"total_credit"`
	ClosingBalance int64     `db:"closing_balance"`
	Status         string    `db:"status"`
	ID             uuid.UUID `db:"id"`
	Version        *int32    `db:"version"`
}

func (q *Queries) UpdateAccountingPerid(ctx context.Context, arg UpdateAccountingPeridParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccountingPerid,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.ClosingBalance,
		arg.Status,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
