// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/google/uuid"
)

type FinanceAccountingPeriod struct {
	ID                   uuid.UUID `db:"id"`
	YearMonth            string    `db:"year_month"`
	StartDate            *int32    `db:"start_date"`
	Interval             *int32    `db:"interval"`
	WalletOpeningBalance int64     `db:"wallet_opening_balance"`
	TotalDebit           *int64    `db:"total_debit"`
	TotalCredit          *int64    `db:"total_credit"`
	WalletClosingBalance *int64    `db:"wallet_closing_balance"`
	WalletID             uuid.UUID `db:"wallet_id"`
}

type FinanceFundProvider struct {
	ID                uuid.UUID `db:"id"`
	Name              string    `db:"name"`
	FpType            string    `db:"fp_type"`
	Balance           int64     `db:"balance"`
	Currency          string    `db:"currency"`
	UnallocatedAmount int64     `db:"unallocated_amount"`
	Version           int32     `db:"version"`
}

type FinanceFundProviderAllocation struct {
	FpID            uuid.UUID `db:"fp_id"`
	WalletID        uuid.UUID `db:"wallet_id"`
	AllocatedAmount int64     `db:"allocated_amount"`
}

type FinanceTransactionRecord struct {
	ID                  uuid.UUID `db:"id"`
	TransactionNo       *string   `db:"transaction_no"`
	TransactionType     string    `db:"transaction_type"`
	Amount              int64     `db:"amount"`
	WalletBalance       int64     `db:"wallet_balance"`
	WalletID            uuid.UUID `db:"wallet_id"`
	FpID                uuid.UUID `db:"fp_id"`
	FpBalance           int64     `db:"fp_balance"`
	AccountingPeriodsID uuid.UUID `db:"accounting_periods_id"`
}

type FinanceWallet struct {
	ID       uuid.UUID `db:"id"`
	Name     string    `db:"name"`
	Balance  int64     `db:"balance"`
	Currency string    `db:"currency"`
	Version  int32     `db:"version"`
}
