// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: wallet.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

type BulkInsertFundAllocationsParams struct {
	FpID            uuid.UUID
	WalletID        uuid.UUID
	AllocatedAmount int64
}

const createWallet = `-- name: CreateWallet :exec
INSERT INTO finance.wallets (
    id,
    name,
    balance,
    currency,
    version
) VALUES (
    $1, -- id
    $2, -- name
    $3, -- balance
    $4, -- currency
    $5 -- version
)
`

type CreateWalletParams struct {
	ID       uuid.UUID
	Name     string
	Balance  int64
	Currency string
	Version  int32
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) error {
	_, err := q.db.Exec(ctx, createWallet,
		arg.ID,
		arg.Name,
		arg.Balance,
		arg.Currency,
		arg.Version,
	)
	return err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT 
    id,
    name,
    balance,
    currency,
    version
FROM finance.wallets
WHERE id = $1
`

func (q *Queries) GetWalletByID(ctx context.Context, id uuid.UUID) (FinanceWallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, id)
	var i FinanceWallet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.Version,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE finance.wallets
SET
    balance = $1,
    version = version + 1
WHERE id = $2
    AND version = $3
`

type UpdateWalletBalanceParams struct {
	Balance int64
	ID      uuid.UUID
	Version int32
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.Balance, arg.ID, arg.Version)
	return err
}
