// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fund_provider.sql

package dbmodels

import (
	"context"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/finance/app/models"
	"sumni-finance-backend/internal/finance/domain"
)

const fundProviderByUUID = `-- name: FundProviderByUUID :one
SELECT fund_provider_uuid, name, balance, available_balance, currency, fund_provider_type, office_uuid, bank_info, bank_account_number, bank_account_owner, cash_owner_name
FROM finances.fund_providers
WHERE fund_provider_uuid = $1
`

func (q *Queries) FundProviderByUUID(ctx context.Context, fundProviderUuid domain.FundProviderUUID) (FinancesFundProvider, error) {
	row := q.db.QueryRow(ctx, fundProviderByUUID, fundProviderUuid)
	var i FinancesFundProvider
	err := row.Scan(
		&i.FundProviderUuid,
		&i.Name,
		&i.Balance,
		&i.AvailableBalance,
		&i.Currency,
		&i.FundProviderType,
		&i.OfficeUuid,
		&i.BankInfo,
		&i.BankAccountNumber,
		&i.BankAccountOwner,
		&i.CashOwnerName,
	)
	return i, err
}

const fundProvidersByUUIDs = `-- name: FundProvidersByUUIDs :many
SELECT fund_provider_uuid, name, balance, available_balance, currency, fund_provider_type, office_uuid, bank_info, bank_account_number, bank_account_owner, cash_owner_name
FROM finances.fund_providers
WHERE fund_provider_uuid = ANY($1::UUID[])
`

func (q *Queries) FundProvidersByUUIDs(ctx context.Context, fundProviderUuids []common.UUID) ([]FinancesFundProvider, error) {
	rows, err := q.db.Query(ctx, fundProvidersByUUIDs, fundProviderUuids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinancesFundProvider{}
	for rows.Next() {
		var i FinancesFundProvider
		if err := rows.Scan(
			&i.FundProviderUuid,
			&i.Name,
			&i.Balance,
			&i.AvailableBalance,
			&i.Currency,
			&i.FundProviderType,
			&i.OfficeUuid,
			&i.BankInfo,
			&i.BankAccountNumber,
			&i.BankAccountOwner,
			&i.CashOwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFundProvider = `-- name: InsertFundProvider :exec
INSERT INTO finances.fund_providers (
    fund_provider_uuid,
    name,
    balance,
    available_balance,
    currency,
    fund_provider_type,
    bank_info,
    bank_account_number,
    bank_account_owner,
    cash_owner_name,
    office_uuid
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type InsertFundProviderParams struct {
	FundProviderUuid  domain.FundProviderUUID
	Name              string
	Balance           decimal.Decimal
	AvailableBalance  decimal.Decimal
	Currency          shared.Currency
	FundProviderType  domain.FundProviderType
	BankInfo          shared.BankInfo
	BankAccountNumber *string
	BankAccountOwner  *string
	CashOwnerName     *string
	OfficeUuid        models.OfficeUUID
}

func (q *Queries) InsertFundProvider(ctx context.Context, arg InsertFundProviderParams) error {
	_, err := q.db.Exec(ctx, insertFundProvider,
		arg.FundProviderUuid,
		arg.Name,
		arg.Balance,
		arg.AvailableBalance,
		arg.Currency,
		arg.FundProviderType,
		arg.BankInfo,
		arg.BankAccountNumber,
		arg.BankAccountOwner,
		arg.CashOwnerName,
		arg.OfficeUuid,
	)
	return err
}

const updateFundProviderBalance = `-- name: UpdateFundProviderBalance :exec
UPDATE finances.fund_providers
SET 
    balance = COALESCE($1, balance),
    available_balance =  COALESCE($2, available_balance)
WHERE
    fund_provider_uuid = $3
`

type UpdateFundProviderBalanceParams struct {
	Balance          *decimal.Decimal
	AvailableBalance *decimal.Decimal
	FundProviderUuid domain.FundProviderUUID
}

func (q *Queries) UpdateFundProviderBalance(ctx context.Context, arg UpdateFundProviderBalanceParams) error {
	_, err := q.db.Exec(ctx, updateFundProviderBalance, arg.Balance, arg.AvailableBalance, arg.FundProviderUuid)
	return err
}
