// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package dbmodels

import (
	"context"

	"github.com/shopspring/decimal"
	"sumni-finance-backend/internal/common/shared"
	"sumni-finance-backend/internal/finance/app/models"
	"sumni-finance-backend/internal/finance/domain"
)

const fundProvidersWithAllocations = `-- name: FundProvidersWithAllocations :many
SELECT 
    fpa.wallet_uuid, fpa.fund_provider_uuid, fpa.allocation_amount,
    fp.fund_provider_uuid, fp.name, fp.balance, fp.available_balance, fp.currency, fp.fund_provider_type, fp.bank_name, fp.bank_account_number, fp.bank_account_owner, fp.cash_owner_name, fp.office_uuid
FROM finances.fund_provider_allocations fpa
    INNER JOIN finances.fund_providers fp ON fpa.fund_provider_uuid = fp.fund_provider_uuid
WHERE fpa.wallet_uuid = $1
`

type FundProvidersWithAllocationsRow struct {
	FinancesFundProviderAllocation FinancesFundProviderAllocation
	FinancesFundProvider           FinancesFundProvider
}

func (q *Queries) FundProvidersWithAllocations(ctx context.Context, walletUuid domain.WalletUUID) ([]FundProvidersWithAllocationsRow, error) {
	rows, err := q.db.Query(ctx, fundProvidersWithAllocations, walletUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FundProvidersWithAllocationsRow{}
	for rows.Next() {
		var i FundProvidersWithAllocationsRow
		if err := rows.Scan(
			&i.FinancesFundProviderAllocation.WalletUuid,
			&i.FinancesFundProviderAllocation.FundProviderUuid,
			&i.FinancesFundProviderAllocation.AllocationAmount,
			&i.FinancesFundProvider.FundProviderUuid,
			&i.FinancesFundProvider.Name,
			&i.FinancesFundProvider.Balance,
			&i.FinancesFundProvider.AvailableBalance,
			&i.FinancesFundProvider.Currency,
			&i.FinancesFundProvider.FundProviderType,
			&i.FinancesFundProvider.BankName,
			&i.FinancesFundProvider.BankAccountNumber,
			&i.FinancesFundProvider.BankAccountOwner,
			&i.FinancesFundProvider.CashOwnerName,
			&i.FinancesFundProvider.OfficeUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWallet = `-- name: InsertWallet :exec
INSERT INTO finances.wallets (
    wallet_uuid,
    name,
    description,
    balance,
    currency,
    office_uuid
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertWalletParams struct {
	WalletUuid  domain.WalletUUID
	Name        string
	Description string
	Balance     decimal.Decimal
	Currency    shared.Currency
	OfficeUuid  models.OfficeUUID
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) error {
	_, err := q.db.Exec(ctx, insertWallet,
		arg.WalletUuid,
		arg.Name,
		arg.Description,
		arg.Balance,
		arg.Currency,
		arg.OfficeUuid,
	)
	return err
}

const upsertFundProviderAllocations = `-- name: UpsertFundProviderAllocations :exec
INSERT INTO finances.fund_provider_allocations (
    wallet_uuid,
    fund_provider_uuid,
    allocation_amount
)
VALUES ($1, $2, $3)
ON CONFLICT (wallet_uuid, fund_provider_uuid) 
    DO UPDATE SET
        allocation_amount = EXCLUDED.allocation_amount
`

type UpsertFundProviderAllocationsParams struct {
	WalletUuid       domain.WalletUUID
	FundProviderUuid domain.FundProviderUUID
	AllocationAmount decimal.Decimal
}

func (q *Queries) UpsertFundProviderAllocations(ctx context.Context, arg UpsertFundProviderAllocationsParams) error {
	_, err := q.db.Exec(ctx, upsertFundProviderAllocations, arg.WalletUuid, arg.FundProviderUuid, arg.AllocationAmount)
	return err
}

const walletByUUID = `-- name: WalletByUUID :one
SELECT wallet_uuid, name, description, balance, currency, office_uuid
FROM finances.wallets
WHERE wallet_uuid = $1
`

func (q *Queries) WalletByUUID(ctx context.Context, walletUuid domain.WalletUUID) (FinancesWallet, error) {
	row := q.db.QueryRow(ctx, walletByUUID, walletUuid)
	var i FinancesWallet
	err := row.Scan(
		&i.WalletUuid,
		&i.Name,
		&i.Description,
		&i.Balance,
		&i.Currency,
		&i.OfficeUuid,
	)
	return i, err
}
