// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	ledger "sumni-finance-backend/internal/finance/domain/ledger"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateAccountingPeriod provides a mock function with given fields: ctx, wID, ap
func (_m *MockRepository) CreateAccountingPeriod(ctx context.Context, wID uuid.UUID, ap *ledger.AccountingPeriod) error {
	ret := _m.Called(ctx, wID, ap)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccountingPeriod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *ledger.AccountingPeriod) error); ok {
		r0 = rf(ctx, wID, ap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateAccountingPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccountingPeriod'
type MockRepository_CreateAccountingPeriod_Call struct {
	*mock.Call
}

// CreateAccountingPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - wID uuid.UUID
//   - ap *ledger.AccountingPeriod
func (_e *MockRepository_Expecter) CreateAccountingPeriod(ctx interface{}, wID interface{}, ap interface{}) *MockRepository_CreateAccountingPeriod_Call {
	return &MockRepository_CreateAccountingPeriod_Call{Call: _e.mock.On("CreateAccountingPeriod", ctx, wID, ap)}
}

func (_c *MockRepository_CreateAccountingPeriod_Call) Run(run func(ctx context.Context, wID uuid.UUID, ap *ledger.AccountingPeriod)) *MockRepository_CreateAccountingPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*ledger.AccountingPeriod))
	})
	return _c
}

func (_c *MockRepository_CreateAccountingPeriod_Call) Return(_a0 error) *MockRepository_CreateAccountingPeriod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateAccountingPeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID, *ledger.AccountingPeriod) error) *MockRepository_CreateAccountingPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
