// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	wallet "sumni-finance-backend/internal/finance/domain/wallet"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) Create(ctx context.Context, _a1 *wallet.Wallet) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *wallet.Wallet) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *wallet.Wallet
func (_e *MockRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, _a1 *wallet.Wallet)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*wallet.Wallet))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *wallet.Wallet) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAllocations provides a mock function with given fields: ctx, wID, allocationSpec, allocatedFunc
func (_m *MockRepository) CreateAllocations(ctx context.Context, wID uuid.UUID, allocationSpec wallet.ProviderAllocationSpec, allocatedFunc func(*wallet.Wallet) error) error {
	ret := _m.Called(ctx, wID, allocationSpec, allocatedFunc)

	if len(ret) == 0 {
		panic("no return value specified for CreateAllocations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, wallet.ProviderAllocationSpec, func(*wallet.Wallet) error) error); ok {
		r0 = rf(ctx, wID, allocationSpec, allocatedFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAllocations'
type MockRepository_CreateAllocations_Call struct {
	*mock.Call
}

// CreateAllocations is a helper method to define mock.On call
//   - ctx context.Context
//   - wID uuid.UUID
//   - allocationSpec wallet.ProviderAllocationSpec
//   - allocatedFunc func(*wallet.Wallet) error
func (_e *MockRepository_Expecter) CreateAllocations(ctx interface{}, wID interface{}, allocationSpec interface{}, allocatedFunc interface{}) *MockRepository_CreateAllocations_Call {
	return &MockRepository_CreateAllocations_Call{Call: _e.mock.On("CreateAllocations", ctx, wID, allocationSpec, allocatedFunc)}
}

func (_c *MockRepository_CreateAllocations_Call) Run(run func(ctx context.Context, wID uuid.UUID, allocationSpec wallet.ProviderAllocationSpec, allocatedFunc func(*wallet.Wallet) error)) *MockRepository_CreateAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(wallet.ProviderAllocationSpec), args[3].(func(*wallet.Wallet) error))
	})
	return _c
}

func (_c *MockRepository_CreateAllocations_Call) Return(_a0 error) *MockRepository_CreateAllocations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateAllocations_Call) RunAndReturn(run func(context.Context, uuid.UUID, wallet.ProviderAllocationSpec, func(*wallet.Wallet) error) error) *MockRepository_CreateAllocations_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransactionRecords provides a mock function with given fields: ctx, wID, allocationSpec, accountingPeriodIDs, updateFunc
func (_m *MockRepository) CreateTransactionRecords(ctx context.Context, wID uuid.UUID, allocationSpec wallet.ProviderAllocationSpec, accountingPeriodIDs uuid.UUID, updateFunc func(*wallet.Wallet) error) error {
	ret := _m.Called(ctx, wID, allocationSpec, accountingPeriodIDs, updateFunc)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransactionRecords")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, wallet.ProviderAllocationSpec, uuid.UUID, func(*wallet.Wallet) error) error); ok {
		r0 = rf(ctx, wID, allocationSpec, accountingPeriodIDs, updateFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateTransactionRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransactionRecords'
type MockRepository_CreateTransactionRecords_Call struct {
	*mock.Call
}

// CreateTransactionRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - wID uuid.UUID
//   - allocationSpec wallet.ProviderAllocationSpec
//   - accountingPeriodIDs uuid.UUID
//   - updateFunc func(*wallet.Wallet) error
func (_e *MockRepository_Expecter) CreateTransactionRecords(ctx interface{}, wID interface{}, allocationSpec interface{}, accountingPeriodIDs interface{}, updateFunc interface{}) *MockRepository_CreateTransactionRecords_Call {
	return &MockRepository_CreateTransactionRecords_Call{Call: _e.mock.On("CreateTransactionRecords", ctx, wID, allocationSpec, accountingPeriodIDs, updateFunc)}
}

func (_c *MockRepository_CreateTransactionRecords_Call) Run(run func(ctx context.Context, wID uuid.UUID, allocationSpec wallet.ProviderAllocationSpec, accountingPeriodIDs uuid.UUID, updateFunc func(*wallet.Wallet) error)) *MockRepository_CreateTransactionRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(wallet.ProviderAllocationSpec), args[3].(uuid.UUID), args[4].(func(*wallet.Wallet) error))
	})
	return _c
}

func (_c *MockRepository_CreateTransactionRecords_Call) Return(_a0 error) *MockRepository_CreateTransactionRecords_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateTransactionRecords_Call) RunAndReturn(run func(context.Context, uuid.UUID, wallet.ProviderAllocationSpec, uuid.UUID, func(*wallet.Wallet) error) error) *MockRepository_CreateTransactionRecords_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, wID
func (_m *MockRepository) GetByID(ctx context.Context, wID uuid.UUID) (*wallet.Wallet, error) {
	ret := _m.Called(ctx, wID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *wallet.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*wallet.Wallet, error)); ok {
		return rf(ctx, wID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *wallet.Wallet); ok {
		r0 = rf(ctx, wID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, wID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - wID uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, wID interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, wID)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, wID uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 *wallet.Wallet, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*wallet.Wallet, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDWithProviders provides a mock function with given fields: ctx, wID, spec
func (_m *MockRepository) GetByIDWithProviders(ctx context.Context, wID uuid.UUID, spec wallet.ProviderAllocationSpec) (*wallet.Wallet, error) {
	ret := _m.Called(ctx, wID, spec)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithProviders")
	}

	var r0 *wallet.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, wallet.ProviderAllocationSpec) (*wallet.Wallet, error)); ok {
		return rf(ctx, wID, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, wallet.ProviderAllocationSpec) *wallet.Wallet); ok {
		r0 = rf(ctx, wID, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, wallet.ProviderAllocationSpec) error); ok {
		r1 = rf(ctx, wID, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByIDWithProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDWithProviders'
type MockRepository_GetByIDWithProviders_Call struct {
	*mock.Call
}

// GetByIDWithProviders is a helper method to define mock.On call
//   - ctx context.Context
//   - wID uuid.UUID
//   - spec wallet.ProviderAllocationSpec
func (_e *MockRepository_Expecter) GetByIDWithProviders(ctx interface{}, wID interface{}, spec interface{}) *MockRepository_GetByIDWithProviders_Call {
	return &MockRepository_GetByIDWithProviders_Call{Call: _e.mock.On("GetByIDWithProviders", ctx, wID, spec)}
}

func (_c *MockRepository_GetByIDWithProviders_Call) Run(run func(ctx context.Context, wID uuid.UUID, spec wallet.ProviderAllocationSpec)) *MockRepository_GetByIDWithProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(wallet.ProviderAllocationSpec))
	})
	return _c
}

func (_c *MockRepository_GetByIDWithProviders_Call) Return(_a0 *wallet.Wallet, _a1 error) *MockRepository_GetByIDWithProviders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByIDWithProviders_Call) RunAndReturn(run func(context.Context, uuid.UUID, wallet.ProviderAllocationSpec) (*wallet.Wallet, error)) *MockRepository_GetByIDWithProviders_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
