name: Acceptance Stage

on:
  repository_dispatch:
    types: [deploy-backend-staging]

env:
  IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
concurrency:
  group: acceptance-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-24.04
    steps:
      - name: Dispatch deploy to staging
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: https://github.com/quangbach27/sumni-finance-deployment
          event-type: deploy-backend          
          client-payload: '{"image_tag": "${{ github.event.client_payload.image_tag }}", "env": "staging"}'