name: Acceptance Stage

on:
  repository_dispatch:
    types: [acceptance-stage]
env:
  IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
concurrency:
  group: acceptance-finance-backend-stage
  cancel-in-progress: true
jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - name: Dispatch deploy to staging
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          repository: quangbach27/sumni-finance-deployment
          event-type: deploy-backend
          client-payload: '{"image_tag": "${{ github.event.client_payload.image_tag }}", "env": "staging"}'
